### ISSUE TITLE
Input Selection via pure JSON Schema

### ISSUE THREAD

**Issue by rado0x54** [decentralized-identity/presentation-exchange#11]
On  the C&C call on 2/12, it was suggested by @OR13, that the `input selection` logic could be modeled purely with JSON Schema. This issue tracks my progress on modeling this accordingly.

**Comment by csuwildcat** [comment]
I looked at JSON Schema and JSON Logic for the selection rule stuff, and it basically wasn't possible, and there weren't even extensions that would do the basic case. I think we might be over complicating the selection piece, and should just specify the two rules and spec language. Using JSON Schema for the input *descriptors* might be more feasible, however.

**Comment by rado0x54** [comment]
I have the same feeling. I was not even looking at JSON Logic yet but have a hard time modeling the set logic with the limited descriptors of JSON Schema. (I thought this was the goal). Maybe let's sync on what approach we should focus our energy now.

**Comment by OR13** [comment]
Any update on this? it would be very relevant to the ongoing debate here:
https://github.com/w3c-ccg/vc-issuer-http-api/pull/18

**Comment by OR13** [comment]
I think this ship has sailed and we support a custom algebra defined in the spec, along with JSONPath, JSONSchema and Filter... closing.
