### ISSUE TITLE
Provide an example of Presentation Request

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/presentation-exchange#112]
[The current spec says](https://identity.foundation/presentation-exchange/#presentation-requests):
> Presentation Definitions may be sent from a Verifier to a Holder using a wide variety of transport mechanisms or credentials exchange protocols. This specification does not define a transport mechanism for Presentation Definitions (or Presentation Request), but does note that different use cases, supported signature schemes, protocols, and threat models may require a Presentation Request to have certain properties 

It is unclear to me whether a Presentation Definition is the same as a Presentation Request, or if a Presentation Request is an additional property in the Presentation Definition.

Anyways, @csuwildcat @glcohen @wyc could please provide an example for a Presentation Definition + Presentation Request (that uses `challenge` and `domain`)? 

We should add that example to the spec.

The reason why I'm asking is that we might be able to use Presentation Requests in [Aries 0511](https://github.com/hyperledger/aries-rfcs/blob/master/features/0511-dif-cred-manifest-attach/README.md#propose-credential-attachment-format) rather than adding `domain` and `challenge` as individual parameters. [See this issue for info on the context](https://github.com/hyperledger/aries-rfcs/issues/538).

**Comment by csuwildcat** [comment]
The PE spec does not define the outer request - there is no such object/format defined in the spec. You are to use the Presentation Definition/Submission objects in existing outer wrappers that handle generic auth/request-related aspects of data exchange.

**Comment by llorllale** [comment]
I agree with @csuwildcat and further note the spec is clear enough in this regard IMO.

**Comment by llorllale** [comment]
Related: #52

**Comment by glcohen** [comment]
Language should be clarified. We could consider examples like we do with submissions (VPs, tokens, etc). There is no VP equivalent for a request -- essentially a signed piece of json containing the request could work, or an ID token.

**Comment by brentzundel** [comment]
A Presentation Request is a transport mechanism for Presentation Definitions.
I think this issue will be resolved by adding Presentation Request to the terminology.

**Comment by awoie** [comment]
@brentzundel imo, we can resolve this issue by adding the presentation request to the terminology section.

**Comment by glcohen** [comment]
https://github.com/decentralized-identity/presentation-exchange/pull/152
