### ISSUE TITLE
Input Descriptor for a self-attested presentation of a DID?

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/presentation-exchange#113]
@csuwildcat @wyc @glcohen Is it possible to ask for a presentation of the DID of the holder and nothing else? What would be the `input_descriptor` object?

**Comment by glcohen** [comment]
Of course, but it would be dependent on where you know a DID resides. Traditionally, we can assume that a VC contains a DID. With selective disclosure it's possible to request just the DID like this...

```
{
  "input_descriptors": [
    {
      "id": "did_input",
      "schema": {
        "uri": [
          "https://schema-with-did.com/did-schema.json"
        ],
        "name": "Any Schema That Has a DID",
        "purpose": "We need your DID."
      },
      "constraints": {
        "limit_disclosure": true,
        "fields": [
          {
            "path": [
              "$.credentialSubject.id"
            ],
            "purpose": "We need your DID from a VC",
            "filter": {
              "type": "string",
              "pattern": "did:*:*"
            }
          }
        ]
      }
    }
  ]
}
```

Because of the nature of pres exchange I'm struggling to come up with a way to request a DID that avoids you knowing the schema of a document that contains a DID beforehand.

**Comment by brentzundel** [comment]
If the verifier uses the `subject_is_issuer` field, the holder can simply produce a VC that matches the requested path (and therefore should match the indicated schema). For example:
```
{
  "input_descriptors": [
    {
      "id": "did_input",
      "schema": {
        "uri": [
          "https://schema-with-did.com/did-schema.json"
        ],
        "name": "Any Schema That Has a DID",
        "purpose": "We need your DID."
      },
      "constraints": {
        "limit_disclosure": true,
        "subject_is_issuer": "preferred",
        "fields": [
          {
            "path": [
              "$.credentialSubject.id"
            ],
            "purpose": "We need your DID from a VC",
            "filter": {
              "type": "string",
              "pattern": "did:*:*"
            }
          }
        ]
      }
    }
  ]
}
```
This also might be related to the PR that someday I will actually produce that will cover holder binding.

**Comment by awoie** [comment]
@brentzundel @glcohen thanks for your answers. that makes sense. @brentzundel looking forward to the holder binding section.

**Comment by csuwildcat** [comment]
Satisfied by the holder binding PR
