### ISSUE TITLE
Bias for JWT in spec

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#114]
> The object MUST include a format property, and its value MUST be a string value matching one of the Credential Format Designation (jwt, jwt_vc, jwt_vp), to denote what data format the credential is being submitted in.

**Comment by glcohen** [comment]
Is this a problem, the linked section at the end of that sentence provides the full list https://identity.foundation/presentation-exchange/#credential-format-designations

A PR is encouraged if you wish to improve 😄

**Comment by OR13** [comment]
PR up.

**Comment by glcohen** [comment]
Addressed in #117
