### ISSUE TITLE
I object to the publication of this specification as a stable version

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#115]
Per the contributing guidelines defined

https://github.com/decentralized-identity/presentation-exchange/blob/master/contributing.md#assigning-section-content-in-the-stable-state

> When the WG has consensus that the above conditions have been reached, the section enters a final 2-week comment period if no substantive objections are raised against the LAST-COMMENTS status. The start of this period, intended for "last comments," should be announced on the Working Group mailing list. If substantial discussion or change happens, this LAST-COMMENTS phase can be extended 1 additional week at the discretion of the chairs.

I object to the use of spec-up as the specification tool used to produce this specification.

spec up is not maintained by DIF and has 1 contributor.

spec up has not been approved for the delivery of specifications that meet the guidelines of a standards organization.

DIF has not approved spec up for delivery of stable specifications.

DIF has no formal requirements for specifications documented anywhere. The DIF charter notes this is up to the working group to decide.

For those looking for "versions" of this spec, please use the internet archive, as there is no formal versioning / release process defined for this specification today:

https://web.archive.org/web/20200924173605/https://identity.foundation/presentation-exchange/

**Comment by glcohen** [comment]
The spec is functional and understood by all who view it. To me, this point is nit-picky and impedes progress.

Perhaps we should get "official DIF approval" for the use of spec-up. It has already been presented at DIF-wide meetings, which I presumed was sufficient.

**Comment by OR13** [comment]
> To me, this point is nit-picky and impedes progress.

I have proposed DIF approve spec-up and/or other tools for official use, to resolve this issue.

I am following the contributing guide for this repo, and acting in what I believe is the best interest of contributors to the spec, and DIF as a whole.

> Exactly why this isn't an issue.

I am a member of the working group and contributor to this spec, and I never "decided" to use spec-up.

That being said, if there is a vote, and I am in the minority I am happy to "let each working group at DIF decide how they want to publish specs".

I think for DIF and Members, Having clear guidelines and encouraging working groups to work on specs with tools where the skill is transferable (skill using IETF / W3C tooling is more valuable than skill using a custom tool), is preferred. Hence my objection.

**Comment by glcohen** [comment]
I'm in favor of having DIF pick up spec-up and additionally having a group discussion/vote on which tool to use. We can discuss at the next meeting.

**Comment by brentzundel** [comment]
I'm going to raise a PR that modifies the contributing.md document to more closely reflect the process we've been following as a group, and to propose a way of continuing. roughly:
1. we triage issues according to the next version or some future version
2. Once all issues for a particular version have been addressed, we vote as a group whether to release that version.
3. If the group agrees to publish a particular version, they may also add a status descriptor for the spec as a whole.
4. If the group does not agree to publish, they will identify what additional issues must be addressed in order to reach agreement.

**Comment by OR13** [comment]
@brentzundel thanks, thats exactly the kind of process I am hoping for.... for DIF as a whole.... if each WG gets a different version, I guess thats better than what we have now, and I will take whatever I can get :)

**Comment by brentzundel** [comment]
Created PR #131 to try and address this.
comments welcome

**Comment by glcohen** [comment]
#131 was merged. @OR13 please re-open if you feel closing was premature.
