### ISSUE TITLE
Add IANA considerations section

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/presentation-exchange#116]
To use `presentation_submission`, `presentation_definition` etc. in JWT/JWS in a collision resistant free manner we should add all relevant terms (claims) to IANA. Normally, specs do include an IANA considerations sections for this and the editors/chairs should send them in .

**Comment by glcohen** [comment]
Can you give a bit more detail for us less knowledgable on IANA?

**Comment by awoie** [comment]
There is a best practice document here: https://tools.ietf.org/html/rfc8126, OpenID Connect has a good example here: https://openid.net/specs/openid-connect-core-1_0.html#IANA. It basically describes what elements of the spec relate to IANA such as the claims registry.

**Comment by awoie** [comment]
@glcohen I can provide a PR.

**Comment by glcohen** [comment]
Thank you @awoie !

**Comment by glcohen** [comment]
Solved in #124
