### ISSUE TITLE
Attribute source enforcement 

### ISSUE THREAD

**Issue by dtmcg** [decentralized-identity/presentation-exchange#13]
For the VC request is a restriction required (explicit or implicit) to ensure that requested attributes are sourced from the same credential. There is a relative context for attributes in a VC which may be important for some selection 
For example challenge for the date, currency and value of a payslip. It is resonable that the verifier would require all three fields to be sourced from the same credential. An example where that may not be important is for contact details where a primary and secondary address may be sourced from different VCs.

**Comment by OR13** [comment]
I think this is a request for a specific example. @dtmcg can you provide one for the spec?

**Comment by swcurran** [comment]
Looks to be the same as #27 - perhaps close this?

**Comment by csuwildcat** [comment]
Will be addressing in the scope of Issue https://github.com/decentralized-identity/presentation-exchange/issues/27
