### ISSUE TITLE
Provide a way to express the format/encoding of mapped inputs

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#15]
In the case of a presentation definition:
```
      "constraints": {
        "fields": [
          {
            "path": ["$.vc.issuer"],
// ...
```

What if the `$.vc` field is a JWT encoded blob? Do we support de-encoding to operate? Are we ignoring any signatures? Do we support any other encodings? What're the rules around this?

**Comment by glcohen** [comment]
Look into advocating for the usage of https://github.com/multiformats/multiformats for encoded blobs

**Comment by csuwildcat** [comment]
Resolution: add target credential format type and encoding properties to Presentation Submission.

**Comment by csuwildcat** [comment]
Proposal: add format and encoding indicators to the Presentation Submission descriptor mapping objects, wherein the value of the `encoding` property is the long-form string identifiers from the multibase list:

```json
"presentation_submission": {
    "descriptor_map": [
      {   
        "id": "contoso_credential",
        "format": "jwt",
        "encoding": "base64url",
        "path": "$.verifiableCredential.[0]"
      }
    ]
  }
}
```

**Comment by csuwildcat** [comment]
@wyc @brentzundel What do you think? ^

**Comment by OR13** [comment]
Exact credential formats must be committed to the repo in order to discuss this. @csuwildcat please check in some sample credentials matching this format.

**Comment by csuwildcat** [comment]
@OR13 I would like to discuss and get acceptance on the overall asks/intent here before hopping to provision of the values and strings we might use for these properties.

**Comment by csuwildcat** [comment]
There is also the desire by some to add a signature/crypto scheme definition, so the presenter/verifier can know what of those are accepted and being digested.

**Comment by csuwildcat** [comment]
To provide a fuller example:

```json5
"presentation_submission": {
    "descriptor_map": [
      {
        "id": "bank_input",
        "path": "$.credentials.[0]"
      },
      {
        "id": "employment_input",
        "path": "$.credentials.[1]"
      }
    ]
  },
  "credentials: [

   // a base64url encoded JWT
     "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwcz
      ovL3NlcnZlci5vdGhlcm9wLmNvbSIsInN1YiI6ImU4MTQ4NjAzLTg5MzQtNDI0N
      S04MjViLWMxMDhiOGI2Yjk0NSIsInZlcmlmaWVkX2NsYWltcyI6eyJ2ZXJpZmlj
      YXRpb24iOnsidHJ1c3Rf",

    // VC as JSON object
      {...}
  ]
}
```

What we would need is a way for the digesting verifier to know what the target encoding and format of the path-selected payload is. The proposal is to add something like `format`, `encoding`, and `signature` properties to accomplish this:

```json5
"presentation_submission": {
    "descriptor_map": [
      {
        "id": "bank_input",
        "format": "jwt",
        "encoding": "base64url",
        "path": "$.credentials.[0]"
      },
      {
        "id": "employment_input",
        "format": "jwt",
        "encoding": "json",
        "path": "$.credentials.[1]"
      }
    ]
  },
  "credentials: [

   // a base64url encoded JWT
     "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwcz
      ovL3NlcnZlci5vdGhlcm9wLmNvbSIsInN1YiI6ImU4MTQ4NjAzLTg5MzQtNDI0N
      S04MjViLWMxMDhiOGI2Yjk0NSIsInZlcmlmaWVkX2NsYWltcyI6eyJ2ZXJpZmlj
      YXRpb24iOnsidHJ1c3Rf",

    // VC as JSON object
      {...}
  ]
}
```

**Comment by OR13** [comment]
What is a Verifiable Presentation? ... https://www.w3.org/TR/vc-data-model/#presentations

How does it look?.... like this:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://identity.foundation/presentation-exchange/submission/v1",
  ],
  "type": "VerifiablePresentation",
   "presentation_submission": {
    "descriptor_map": [
      {
        "id": "banking_input",
        "path": "$.verifiableCredential.[0]"
      }
    ]
  },
  "verifiableCredential": ["eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwcz
      ovL3NlcnZlci5vdGhlcm9wLmNvbSIsInN1YiI6ImU4MTQ4NjAzLTg5MzQtNDI0N
      S04MjViLWMxMDhiOGI2Yjk0NSIsInZlcmlmaWVkX2NsYWltcyI6eyJ2ZXJpZmlj
      YXRpb24iOnsidHJ1c3Rf", {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "id": "http://example.edu/credentials/1872",
    "type": ["VerifiableCredential", "AlumniCredential"],
    "issuer": "https://example.edu/issuers/565049",
    "issuanceDate": "2010-01-01T19:73:24Z",
    "credentialSubject": {
      "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
      "alumniOf": {
        "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
        "name": [{
          "value": "Example University",
          "lang": "en"
        }, {
          "value": "Exemple d'Université",
          "lang": "fr"
        }]
      }
    },
    "proof": {
      "type": "RsaSignature2018",
      "created": "2017-06-18T21:19:10Z",
      "proofPurpose": "assertionMethod",
      "verificationMethod": "https://example.edu/issuers/keys/1",
      "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X
        sITJX1CxPCT8yAV-TVkIEq_PbChOMqsLfRoPsnsgw5WEuts01mq-pQy7UJiN5mgRxD-WUc
        X16dUEMGlv50aqzpqh4Qktb3rk-BuQy72IFLOqV0G_zS245-kronKb78cPN25DGlcTwLtj
        PAYuNzVBAh4vGHSrQyHUdBBPM"
    }
  }],
  
  "proof": {
    "type": "RsaSignature2018",
    "created": "2018-09-14T21:19:10Z",
    "proofPurpose": "authentication",
    "verificationMethod": "did:example:ebfeb1f712ebc6f1c276e12ec21#keys-1",
    
    "challenge": "1f44d55f-f161-4938-a659-f8026467f126",
    "domain": "4jt78h47fh47",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..kTCYt5
      XsITJX1CxPCT8yAV-TVIw5WEuts01mq-pQy7UJiN5mgREEMGlv50aqzpqh4Qq_PbChOMqs
      LfRoPsnsgxD-WUcX16dUOqV0G_zS245-kronKb78cPktb3rk-BuQy72IFLN25DYuNzVBAh
      4vGHSrQyHUGlcTwLtjPAnKb78"
  }
}
```

What about VC-JWT?.... it looks similar, https://www.w3.org/TR/vc-data-model/#example-31-jwt-payload-of-a-jwt-based-verifiable-presentation-non-normative

... but beware `vc` and `vp` properties have yet to be registered with IANA.....

Obviously JWTs need to be decoded to be usable... the JSON Path values could be applied to the resolute of decode complete... if that where the case, you can actually use the values of the JWT header as well as the payload... which seems... like a requirement... for an example of a decoded JWT see https://github.com/decentralized-identity/presentation-exchange/blob/master/sample-implementation/src/__fixtures__/test-vectors/vc-jwt-decoded.json#L3

The JWT representation of VCs continues to be one of the least well defined things I have ever seen and no one from Microsoft attended the auth wg call to discuss https://github.com/decentralized-identity/did-jose-extensions/blob/master/options.md yesterday...

Please lets not add breaking syntax to the vc data model... a presentation submission should always be a vc data model compliant verifiable presentation.

**Comment by csuwildcat** [comment]
I think you are misunderstanding what this is about: it is a list of input pointers, and once you get those pointers, you need to deal with the values - I don't see how the VC data model stuff comes into this.

**Comment by OR13** [comment]
`bananaOctopus` is breaking syntax for the vc data model, I'm not interested in generating presentation submissions that are not valid verifiable presentations in JWT or LD Proof form.

**Comment by OR13** [comment]
I answered your question, you must decode complete the JWT, then use JSON Path to refer to its members... its important that you use decode complete, you won't have a way to refer to header values.

**Comment by csuwildcat** [comment]
@OR13 I think you are not understanding why I just added the property `bananaOctopus`: this is to show that a Presentation Submission object can be conveyed within literally any type of object, and can select credentials from anywhere in the object, thus your assertions about a specific data model are not applicable. Obviously when inside a particular data format, it would not be `bananaOctopus`, it would be whatever property/structure that format dictated, but of course, Presentation Exchange doesn't care.

**Comment by OR13** [comment]
@csuwildcat my answer still works... it just also happens to be a valid VP... unlike the code snippet you provided...

`"path": "$.verifiableCredential.[0].header.kid"` -> https://github.com/decentralized-identity/presentation-exchange/blob/master/sample-implementation/src/__fixtures__/test-vectors/vc-jwt-decoded.json#L3

`"path": "$.verifiableCredential.[0].header.alg"` -> https://github.com/decentralized-identity/presentation-exchange/blob/master/sample-implementation/src/__fixtures__/test-vectors/vc-jwt-decoded.json#L4

`"path": "$.verifiableCredential.[0].payload.vc.issuanceDate"` -> https://github.com/decentralized-identity/presentation-exchange/blob/master/sample-implementation/src/__fixtures__/test-vectors/vc-jwt-decoded.json#L19

**Comment by csuwildcat** [comment]
@OR13 we cannot predict what the envelop will be, and because of that, the proposed thing above would face a couple issues:

1. You wouldn't know if you it a string somewhere in that selection path whether it was an encoded blob, and what encoding it was, which still implies a need for indicating that in the mapping object.
2. Once you figure out the encoding, you would still need to know what the heck the decoded thing actually was, and I don't think we should tell devs to start doing sniff checks on props to infer it.
3. The signature thing may be the least of the issues, because one could argue that if you decoded the value and understood the format, the format processor will automatically enable application of the right sig stuff.

**Comment by OR13** [comment]
if you replace `verifiableCredential` with `bananaOctopus` does my solution not work? 

`"format": "jwt",`... isn't thats all that is needed to know how to decode complete so you can use JSON Path?

**Comment by csuwildcat** [comment]
> if you replace `verifiableCredential` with `bananaOctopus` does my solution not work?
> 
> `"format": "jwt",`... isn't thats all that is needed to know how to decode complete so you can use JSON Path?

Yes, in a VC type envelop, the property would be `verifiableCredential`, nothing about this Issue is stating otherwise - I am just making the property absurdly generic so people _don't_ get stuck on envelop stuff (because it doesn't apply). I don't think it's wise to conflate the format with the encoding, because there could be cases where a format can be present in different encoded/non-encoded values. For that reason, I would rather have separate properties for format and encoding.

**Comment by OR13** [comment]
We could define a custom table of "format" values... that would account for compact / not compact JWTs... but there are no JWTs that don't use base64url... the less values the better imo... we would be wise to just define what "format" is and enumerate the popular examples... and require people to register new formats before they are valid.

**Comment by csuwildcat** [comment]
Personally, I would rather separate them, because if we ever run into a format that can be presented in multiple ways, I would hate to have a registry with values like: `credformat-base58`, `credformat-base64url`, `credformat` (last one meaning: no encoding different than the envelope's own encoding).

**Comment by csuwildcat** [comment]
For the encoding part, I would hope to reuse a well done existing table of encoding designations, like this: https://github.com/multiformats/multibase#multibase-table

Not sure if one exists for the formats, but happy to reuse something there too.

**Comment by OR13** [comment]
issue should be renamed... PE Spec has `descriptor_map.encoding` table or PE Spec supports multiple encodings for the same assertion format.... serialized blobs... it's not accurate.... one to definitely include would be base64url encoded CWTs.

**Comment by csuwildcat** [comment]
Action items and questions from call:

1. Enable specification of more aspects of the cryptographic configuration than just suite-level specificity across formats.
2. Are there any means to specify within a JSON LD signature suite to select a subset of supported algorithms/properties?

**Comment by csuwildcat** [comment]
Merged in latest PR
