### ISSUE TITLE
Clarifying format schema

### ISSUE THREAD

**Issue by NickDarvey** [decentralized-identity/presentation-exchange#150]
Is `alg` a required property for `jwt*` formats, and `proof_type` a required property for `ldp*` formats? The JSON Schema says it is but I think the docs could read either way:

```markdown
- The resource ****MAY**** include a `format` property, and its value 
  ****MUST**** be an object with one or more properties matching the registered 
  [Claim Format Designations](#claim-format-designations) (`jwt`, 
  `jwt_vc`, `jwt_vp`, etc.) to inform the Holder of the claim format 
  configurations the [[ref:Verifier]] can process. The value for each property included 
  ****MUST**** be an object composed as follows:
    - The object ****MAY**** include a format-specific property (i.e. `alg`, 
      `proof_type`) that expresses which algorithms the [[ref:Verifier]] supports for the 
      format, and if present, its value ****MUST**** be an array of one or more 
      of the format-specific algorithmic identifier references, as noted in the 
      [Claim Format Designations](#claim-format-designations) section.
```

https://github.com/decentralized-identity/presentation-exchange/blob/master/spec/spec.md#L493-L503

Specifically this:
>its value MUST be an object with one or more properties matching the registered Claim Format Designations

seems to contradict this:
>The object MAY include a format-specific property

I think we could update that second statment to be a 'MUST'? Alternatively we could change the `one or more properties` to `zero or more properties` and drop the 'required' for them from the JSON Schema.

**Comment by csuwildcat** [comment]
PROPOSAL: Change the MAY to a MUST

**Comment by csuwildcat** [comment]
This was changed to a MUST in latest PR
