### ISSUE TITLE
Need stricter linkage between Definitions and Submissions

### ISSUE THREAD

**Issue by glcohen** [decentralized-identity/presentation-exchange#154]
How do I know that a presentation submission is for a certain presentation definition/request?

We have no requirement on Presentation Definition identifiers. The only mention of such linkage between a request and a submission is in the input descriptors -- https://identity.foundation/presentation-exchange/#presentation-submission. 

I'd like to propose adding a required top-level `id` property to both Presentation Definitions and Presentation Submissions. Presentation Submissions will add an additional `definition_id` property that lists the `id` of the Definition the Submission correlates to.

**Comment by OR13** [comment]
yes, this is similar to the self describing schemas feature:

https://github.com/snowplow/iglu/wiki/Self-describing-JSON-Schemas

https://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/

```
{ "schema": "iglu:com.snowplowanalytics/ad_click/jsonschema/1-0-0", "data": { "bannerId": "4732ce23d345" } }
```
