### ISSUE TITLE
Need to fix metadata definition

### ISSUE THREAD

**Issue by soluchok** [decentralized-identity/presentation-exchange#156]
According to JSON Schema https://identity.foundation/presentation-exchange/#json-schema-2 metadata is defined as `"metadata": { "type": "string" }`. But spec says "value MUST be an object with metadata properties" which means `{} != ""`. I assume that metadata should be an object e.g `"metadata": { "type": "object" }`

**Comment by glcohen** [comment]
thanks, I can fix this. though I am surprised to see another golang impl. I would've liked to share one

**Comment by soluchok** [comment]
@glcohen, please share with me :) we just about to start working on the implementation, it would be nice to use an existing one.

**Comment by glcohen** [comment]
https://github.com/workdaycredentials/ledger-common/tree/master/credential/presexchange

happy to move it to DIF to share 😄

**Comment by glcohen** [comment]
https://github.com/decentralized-identity/presentation-exchange/pull/158
