### ISSUE TITLE
is_holder property is described incorrectly 

### ISSUE THREAD

**Issue by soluchok** [decentralized-identity/presentation-exchange#161]
According to spec `is_holder ` is described as following:
* The object MUST contain a field_id property. 
* The object MUST contain a directive property.
See https://github.com/decentralized-identity/presentation-exchange/blob/master/spec/spec.md

The problem is that the example says the opposite `"subject_is_holder": "required"`. See https://github.com/decentralized-identity/presentation-exchange/blob/master/test/presentation-definition/example.json#L37

Also, schema says 
```
"subject_is_holder": {
    "type": "string",
    "enum": ["required", "preferred"]
}
```
See https://github.com/decentralized-identity/presentation-exchange/blob/master/test/presentation-definition/schema.json#L133

As far as I understand `is_holder` should be renamed to `subject_is_holder`.
Second, in the spec `is_holder (subject_is_holder)` should have the same description as `subject_is_issuer` has.

e.g 
```
The object MAY contain a subject_is_holder property, and if present its value MUST be one of the following strings:

required - This indicates that the processing entity MUST submit a response that has been self-attested, i.e., the claim used in the presentation has been 'issued' by the subject of the claim.

preferred - This indicates that it is RECOMMENDED that the processing entity submit a response that has been self-attested, i.e., the claim used in the presentation has been 'issued' by the subject of the claim.
```

**Comment by soluchok** [comment]
@glcohen @csuwildcat

**Comment by brentzundel** [comment]
Thank you for catching this. The definition of `is_holder` was changed in the spec, but wasn't updated in the example or schema.

I added PR #162 to address this inconsistency.
