### ISSUE TITLE
Need clarification on the purpose of a presentation submission; maybe rename?

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/presentation-exchange#166]
I'm pretty familiar with the VC spec and the DID spec, and I've also been following the work on presentation definitions with interest. However, I haven't actually read this spec from beginning to end since I first encountered it many months ago. Following the recent announcement of its status change, I came back to the full doc and its abstract, and immediately found that I had this burning question:

> Why do we need to define a presentation submission? After all, we already know how to submit a presentation. The VC spec stipulates the format for VPs.

After a little reading and studying of the format of the VS, I can now answer my own question: The thing called a "presentation submission" isn't replacing a verifiable presentation; it's explaining how the presented data satisfies the requirements in the preceding request.

My big point here is that this is not at all obvious. There is no sentence in the spec that says, for example, "Don't be confused by a presentation submission's apparent overlap with the format of verifiable presentations. They address two totally different needs. The presentation submission is reconciling what's submitted against the request that preceded it, not providing the data itself (which is the purpose of the verifiable presentation format)."

So here's my suggestion:

1. (Preferred) Rename "presentation submission" to something like "presentation explanation" or "presentation reconciliation" or similar. The word "submission" here is causing a problem because "submission" would naturally be assumed to embody the submitted data, while what this data structure actually embodies is an explanation of how the submitted data satisfies the request.

2. If you're really committed to the name "presentation submission", insert a paragraph or two, right when the concept of the PS is introduced, explaining how it solves a different problem from the VP format.

**Comment by brentzundel** [comment]
Discussed during a meeting on Jan 7, 2021. We settled on `presentation manifest`. @rado0x54 is going to do a PR.

**Comment by rado0x54** [comment]
The PR around this is up: https://github.com/decentralized-identity/presentation-exchange/pull/172

Note:
- Submission Requirements remains unchanged
- Spec Name for `Credential Manifest` will most likely change.

**Comment by rado0x54** [comment]
In today's spec drafting meeting we decided that the name change throughout the spec would be too intrusive and we rather go for option 2 and do an editorial change towards explaining `presentation submission`.

**Comment by csuwildcat** [comment]
Action: add more descriptive language for what the scope of a Presentation Submission is in this spec.
