### ISSUE TITLE
What is the purpose of a purpose?

### ISSUE THREAD

**Issue by RieksJ** [decentralized-identity/presentation-exchange#169]
In many of the examples in the document, there is a field `purpose` which contains a text `we need it`. 

While I can see why it is (currently) there, it sets a bad example, specifically in a text that might become a standard some day, as it condones the behaviour of not taking the time to think for proper content because it doesn't affect the behaviour of the IT.

If the 'purpose' field serves a purpose, please put something in there that adequately demonstrates such purpose. Otherwise, remove it (or leave it blank).

**Comment by TomCJones** [comment]
Here is an example of a purpose that impacts a presentation.
The source data is a patient health record.
The purpose is to prescribe medicine.
The result is that the presentation record must include, (e.g.) allergies.

Another would be location.
The purpose of driving direction would mean that location needed to be fine grained.
The purpose of calculating sales tax would mean that the local city or state must be defined.
The purpose is sensitive information would mean what country where the device is operating must be defined.

**Comment by bumblefudge** [comment]
Addressed thoroughly and vigorously in #187
