### ISSUE TITLE
Rename "Transport Integrations" => "Embed Targets"

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#17]
Place examples for definitions and submissions under this section for each target type.

So that developers can look at 1 section for how to handle a given target.

Provide tab examples under Submission, since we see credential representations there.

**Comment by csuwildcat** [comment]
Remove old section of Transport Integrations

**Comment by csuwildcat** [comment]
Closed via merge of https://github.com/decentralized-identity/presentation-exchange/pull/83
