### ISSUE TITLE
How to account for VC type property?

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/presentation-exchange#170]
The VC spec says ...

> The value of the type property MUST be, or map to (through interpretation of the @context property), one or more URIs. If more than one URI is provided, the URIs MUST be interpreted as an unordered set. Syntactic conveniences SHOULD be used to ease developer usage. Such conveniences might include JSON-LD terms. It is RECOMMENDED that each URI in the type be one which, if dereferenced, results in a document containing machine-readable information about the type.

How are type URIs handled especially with respect to JSON-LD expansion? If you don't expand the @context, then you would get a plain string (not an URI) which imposes the risk of name (type) clashes.

Consider the following VC:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "proof": {  }
}

```
Expanded form is (only type property):

```
"@type": [
      "https://www.w3.org/2018/credentials#VerifiableCredential",
      "https://example.org/examples#UniversityDegreeCredential"
    ]
```

**Comment by csuwildcat** [comment]
I believe the intent here was that you would specify the fully qualified type-based URI, and wallets would use that to scan for creds that match that type-based declaration, which you would have to do as a comparison in wallet code.

**Comment by awoie** [comment]
that makes sense.

**Comment by csuwildcat** [comment]
@awoie is this OK to close now?

**Comment by awoie** [comment]
yes, in case the fully qualified type-based URI is not provided, you would run into some issues. should we make that mandatory explicit add some language to the spec?

**Comment by csuwildcat** [comment]
If clarifying language and an example would help, let's definitely add them. Can you articulate this in a PR?

**Comment by OR13** [comment]
I think perhaps this is a request to show that the format can support linked data, we would need some example json that was "supposed to work" to be pasted here, and then we could go to jsonld playground to check it. ideally we would have tests for this sort of thing.

**Comment by awoie** [comment]
I think at least an informative note would be good.

The issue is at least relevant for `type`, and the specific property names for `credentialSubject` and the VC itself (aka claim names). These properties are URIs (according to the VC spec) but only look nice if JSON-LD is used (together with the `@context`). If no JSON-LD is used, you would need to provide the fully-qualified URI. Because the `presentation_definition` is not JSON-LD, we would still need to require that the `constraints` use the fully-qualified form, right?

```
"constraints": {
          "fields": [
            {
              "path": ["$.credentialSubject.birth_date", "$.vc.credentialSubject.birth_date", "$.birth_date"],
              "filter": {
                "type": "string",
                "format": "date",
                "minimum": "1999-5-16"
              }
            }
          ]
```

**Comment by csuwildcat** [comment]
Action: add fully qualified type URI in examples

**Comment by brentzundel** [comment]
PR #193 addressed this, closing
