### ISSUE TITLE
Unclear what the non-presence of predicate property means

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/presentation-exchange#174]

**Comment by brentzundel** [comment]
So, I should add a sentence to the spec that says, "if a predicate property is absent, the verifier is not requesting a predicate value."

**Comment by csuwildcat** [comment]
@brentzundel I think that's one aspect to make crystal clear, and the other is: if the Verifier doesn't include the property, can you submit a predicate anyway? To the latter question, I was assuming it depends on what signature/proof formats and schemes the Verifier expresses in that formatting section of the PE. Do you agree with that assumption? Either way, I think we might want to something about it.
