### ISSUE TITLE
metadata element is not clearly described

### ISSUE THREAD

**Issue by TomCJones** [decentralized-identity/presentation-exchange#178]
In particular it is unclear what entity it apples to. Consider the example in section 5.3.1. Where metadata contains a "client_id" that is not defined anywhere.  I assume it applies to the verifier, but that is not made clear anywhere.

**Comment by csuwildcat** [comment]
The `metadata` area was left as a free form area for any Verifier-specific properties that may be expressed about a given input being requested. I am was only aware of one group using it, so one might argue for removal.

**Comment by csuwildcat** [comment]
We will add more text noting that it is a Verifier-set property with custom fields they can define for their own purposes.

**Comment by csuwildcat** [comment]
Action: will pull this prop

**Comment by brentzundel** [comment]
PR #198 removes the metadata property.
