### ISSUE TITLE
Consider making top-level id property MAY

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/presentation-exchange#181]

**Comment by OR13** [comment]
prefer `id` be a MUST and that it be an IRI.

**Comment by csuwildcat** [comment]
@OR13 the result of this is that it is absolutely illegal to post/use a presentation exchange object as a template/generic resource or for a submission to be dropped in reference to a generic template of one.

**Comment by OR13** [comment]
> @OR13 the result of this is that it is absolutely illegal to post/use a presentation exchange object as a template/generic resource or for a submission to be dropped in reference to a generic template of one.

Have you read what an IRI is?

`urn:uuid:123...` is an IRI.

I don't see such a requirement doing anything other than helping developers by giving them AT LEAST ONE identifier for the associated JSON resource.

**Comment by csuwildcat** [comment]
We decided to keep everything as is on the last call. I'll close this.
