### ISSUE TITLE
inconsistent limit disclosure flag

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#184]
The `limit_disclosure` constraint currently allows possible values of `true` or `false`.

We may wish to change these to:
  - `required` - which would mean a processing entity MUST limit inputs to those requested in the `presentation definition`
  - `preferred`, which would mean a processing entity SHOULD limit inputs to those requested in the `presentation definition`

(we can also indicate that if the `limit disclosure` property is missing this would mean a processing entity MAY limit inputs to those requested in the `presentation definition`)

This would align the `limit disclosure` flag with the other constraints.

**Comment by tmarkovski** [comment]
Using an `enum` instead a `bool` also allows extending this in the future.
Some more thoughts on cosmetic naming: `limit_disclosure=false` has a double negative in it and takes a bit of thinking to understand the intent. For a data format meant to be human readable, this attribute isn't best described when in negative form. An alternative could be to just use `disclosure` and then describe the possible values for it: `required` and `preferred`. I would also suggest considering `strict` and `lenient` (or similar), which may be more descriptive.

**Comment by bumblefudge** [comment]
Note: I'm updating the examples to use `required`/`preferred`, if you end up going with `strict`/`lenient` or any other enum variation, remember to update the examples accordingly!
