### ISSUE TITLE
Editorial nits (worth discussing Thursday?)

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/presentation-exchange#188]
1. ~~why aren't `Input Descriptor Field Entries` defined in the Terminology? there are dead links to that term throughout (and, to be honest, I found this terminology a little confusing throughout)~~
2. should Martin's and Gabe's affiliations be updated in the frontmatter?
3. Should the status object to be so opinionated/normative when there is a status object registered in the VC extensions registry, and nothing there would support this? It feels like the wrong place to be specifying how status checks work! I didn't update the example of Driver's License Revocation because I was confused about how to proceed, but did update the example LD VC to use a [Revocation-List-2020](https://w3c-ccg.github.io/vc-status-rl-2020/) status object as mentioned in #187. 
4. Forgive me for being that guy, but should hub:// URIs be changed to something that exists today? I feel like using a URI protocol/handler that isn't specified today is needlessly confusing to implementers looking at the spec. One particularly confusing instance of this is the example URIs about passport schemata. Wouldn't it be more logical to assume passport schemata would be hosted on a government schema reference over HTTP for the foreseeable future, the way other USCIS semantics are hosted as part of the [current SVIP sandbox](https://w3c-ccg.github.io/citizenship-vocab/#permanentresidentcard) ? The example makes it sound like an arbitrary DID is hosting government schemata on a hub, which seems to make a lot of assumptions about USCIS infrastructure that seem distracting and untenable given what I know about federal IT policies...

**Comment by brentzundel** [comment]
I fixed the `Input Descriptor Field Entries` links in my terminology clean up PR #192

**Comment by brentzundel** [comment]
May be good to add a line or two clarifying that status may be encoded different ways.

**Comment by brentzundel** [comment]
4) was discussed during the PE call today. No problem with hub:// URLs in examples, but it may be good to add a reference to the hub spec and mention that the URL may not be quite dereferencable just yet.

**Comment by bumblefudge** [comment]
3 & 4 addressed in [this commit](https://github.com/decentralized-identity/presentation-exchange/pull/187/commits/ccfe59ce2c934102f3e6670061d396b62dee3114) in pull #187

**Comment by csuwildcat** [comment]
This was resolved by #187
