### ISSUE TITLE
Presentation Submission is missing top-level context

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/presentation-exchange#195]
The JSON-LD document at:

`https://identity.foundation/presentation-exchange/submission/v1`

is missing the top-level `@context` object that should contain the rest of the document.

**Comment by OR13** [comment]
https://github.com/decentralized-identity/presentation-exchange/blob/master/submission/v1/index.json ?

**Comment by OR13** [comment]
@troyronda  can you include an example of the error you are experiencing with https://www.jsonld-checker.com/

**Comment by troyronda** [comment]
@OR13 Yes - this document is missing the `@context` property that should wrap the rest of the properties.

**Comment by OR13** [comment]
I see... https://w3id.org/security/bbs/v1

**Comment by OR13** [comment]
Does this fix work.... https://github.com/decentralized-identity/presentation-exchange/pull/196

**Comment by troyronda** [comment]
Yes, thanks @OR13
