### ISSUE TITLE
Set-based selection logic vs boolean algebra selection logic

### ISSUE THREAD

**Issue by rado0x54** [decentralized-identity/presentation-exchange#2]
The current proof presentation describes the link between `input_descriptors` and the `input_selection` via a set-based rule mechanism e.g. "Satisfy all of set A", "Pick # of set B".

This requires all `input_descriptors` to be assigned to one or more sets.

An alternative approach to the set-based requirement description could a a boolean algebra approach  where input_descriptors are atomic elements describing the input elements that can be identified uniquely ('e.g. "id", "routing_number"') and input_selection describes a boolean algebra like.
```
[
{
"and": [ "routing_number", "account_number", "idToken"]
},
{
"or": [ "idCard", "passport" ]
}
]
```
This is just a dummy boolean algebra system. I feel there might be good ones out there already. We should use the same on that we use to represent `constraints` on individual `input_descriptors`.
E.g. also see https://stackoverflow.com/questions/20737045/representing-logic-as-data-in-json

**Comment by rado0x54** [comment]
Civic uses the Mongo DB query language to model these conditions in JSON. See this [example](https://docs.mongodb.com/manual/tutorial/query-documents/#specify-and-as-well-as-or-conditions):

**Comment by rado0x54** [comment]
https://github.com/epoberezkin/ajv#validation-keywords

**Comment by csuwildcat** [comment]
I am not seeing anything in JSON Logic, AJV, or Mongo syntaxes to describe the fundamental requirement for multi-option requirement fulfillment: "Pick X from set Y". I would like to timebox this exploration to expire at the next spec meeting, so we can move forward with something. Can we try to see if anything exists to fulfill the multi-option selection use case over the remainder of the week, and if not, just move on?

**Comment by David-Chadwick** [comment]
If by "Pick X from set Y" you are meaning something similar to "present a degree from a UK university" then the way we are addressing this problem is via an ontology that defines the class UK university and each UK university that is a member of this class.

**Comment by csuwildcat** [comment]
> If by "Pick X from set Y" you are meaning something similar to "present a degree from a UK university" then the way we are addressing this problem is via an ontology that defines the class UK university and each UK university that is a member of this class.

No, this is more like a verifying party specifying that they need a certain condition fulfilled, and one of many options may exist to do so - for example: Say I am registering to vote, and it requires proof of citizenship and residence in an area. The citizenship requirement could be fulfilled via a Driver's license, Passport, or State ID, while the residence requirement may be fulfilled via a electric, garbage, or other type of billing statement. In this spec, we are enabling a verifying party to state "Give me X from group Y, and T from group N".

**Comment by David-Chadwick** [comment]
This is simple to specify using a policy tree in CNF. e.g.
(citizen from passport OR citizen from DL OR citizen from StateID) AND (Name and Address from Electric bill OR name and address from Gas bill OR name and address fromf water bill etc)
This is exactly how we specify our policies in JSON

**Comment by David-Chadwick** [comment]
As I said in another post, specifying verifier policies in CNF or DNF allow you to specify any conceivable combination of VCs

**Comment by csuwildcat** [comment]
This has been relatively solidified now, so I am looking to close it in favor of what we have specified in the spec.

**Comment by rado0x54** [comment]
Yes, I agree that we had a clear consensus for a set based logic since it’s a more natural expression syntax then Boolean CNF or DNF.
