### ISSUE TITLE
Need to update specification about limit_disclosure field.

### ISSUE THREAD

**Issue by soluchok** [decentralized-identity/presentation-exchange#201]
According to https://identity.foundation/presentation-exchange `limit_disclosure` is a boolean.
According to schema https://github.com/decentralized-identity/presentation-exchange/blob/master/test/presentation-definition/schema.json `limit_disclosure` is a string.
```
"limit_disclosure": {
    "type": "string",
    "enum": ["required", "preferred"]
},
```
I assume that https://github.com/decentralized-identity/presentation-exchange/blob/master/spec/v1.0.0/index.html was not updated.

**Comment by brentzundel** [comment]
None of the links I'm following show `limit_disclosure` as a boolean. Was this resolved between this issue being created and me looking right now?

**Comment by brentzundel** [comment]
looks like it was fixed here? https://github.com/decentralized-identity/presentation-exchange/pull/202
