### ISSUE TITLE
Update README: include instructions on what to do before pushing

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#21]
Recently, #19 was pushed with a correct `spec.md` but an `index.html` output that was not up to date. #20 fixed this, but really we should have some instructions in the `README.md` on what to ensure before pushing your changes to prevent this from happening again. Note that if you leave `npm run edit` going, then it'll make the changes but you have to remember to add the output file too.

**Comment by OR13** [comment]
yes please, documentation around building and contributing always good to have in the readme.

**Comment by csuwildcat** [comment]
Not release blocker

**Comment by OR13** [comment]
How is documenting how to edit and release version of the spec not the place we are starting?

**Comment by wyc** [comment]
That's actually a good point. @csuwildcat I change my mind and now think we should add this to the milestone. Do you agree?

**Comment by brentzundel** [comment]
On the call 9/17/2020 we agreed this is still a good issue to have in v0.1.0
@csuwildcat @wyc what steps can be taken before our next meeting to move this forward?

**Comment by csuwildcat** [comment]
It now automatically Just Works TM.
