### ISSUE TITLE
Suggestion - remove constraint abstraction to reduce un-necessary nesting

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/presentation-exchange#212]
Currently most of the constraints in the input descriptor are located under the `constraints` JSON member, however I would posit that virtually everything inside the input descriptor object is about conveying what the requestor wants and is hence a constraint. The suggestion is to remove the nesting around the constraint object so the syntax of the input_descriptor is simplified from:

```
{
  "comment": "Note: VP, OIDC, DIDComm, or CHAPI outer wrapper would be here.",
  "presentation_definition": {
    "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
    "input_descriptors": [
      {
        "id": "bankaccount_input",
        "name": "Full Bank Account Routing Information",
        "purpose": "We can only remit payment to a currently-valid bank account, submitted as an ABA RTN + Acct # or IBAN.",
        "schema": [{
            "uri": "https://bank-standards.example.com/fullaccountroute.json"
        }],
        "constraints": {
          "limit_disclosure": "required",
          "fields": [ ...field constraints ]
        }
      }
    ]
  }
}
...
```

To 

```
{
  "comment": "Note: VP, OIDC, DIDComm, or CHAPI outer wrapper would be here.",
  "presentation_definition": {
    "id": "32f54163-7166-48f1-93d8-ff217bdb0653",
    "input_descriptors": [
      {
        "id": "bankaccount_input",
        "name": "Full Bank Account Routing Information",
        "purpose": "We can only remit payment to a currently-valid bank account, submitted as an ABA RTN + Acct # or IBAN.",
        "schema": [{
            "uri": "https://bank-standards.example.com/fullaccountroute.json"
        }],
        "limit_disclosure": "required",
        "fields": [ ...field constraints ]
      }
    ]
  }
}
```

**Comment by Sakurann** [comment]
+1, simplification proposed here is logical and clean.
Since this would be a breaking change, it would be good to get the opinion of existing implementers - if this update to the syntax could be tolerable (also in light of few other updates and potentially going to PE V2.0)

**Comment by brentzundel** [comment]
+1 from me for v2 of PE

**Comment by TimoGlastra** [comment]
I'm generally in favour of this change, but if this is the difference that would require implementations to support a new major version I'd be against it. It doesn't change anything significant about the protocol and will make current implementations 99% the same, but just different enough to introduce complications. I'm particularly interested in what the other changes would be with regards to going to PE v1.1 or 2.0 (as @Sakurann mentioned)

**Comment by csuwildcat** [comment]
Setting a deadline of next Wednesday September 15th to get feedback on whether or not this should still happen.

**Comment by csuwildcat** [comment]
Closing per comment period with resolution to retain the current structure.
