### ISSUE TITLE
Examine other Rules Expression Language before building our own for Submission Requirement

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#22]
Breaking requirements for a rules expression language, aka why we have our own (@csuwildcat):
* Picking between a set: "one of these two", "three of these five"
* Can reference. Looked at JSONLogic, etc. assume what they are selecting over is inside an object, not supporting a reference to an input group such as `"ProofOfAddress"`

Design criteria:
* Use cases using real JWTs/JSON-LDs/etc. must be reasonable
* Usability and understandability is a goal of Presentation Exchange, so humans should be able to make sense of these requirements

(@OR13, @wyc) what are rules expression languages and off-the-shelf tooling relevant to our criteria?
* JSON Logic
* MongoDB Querying

**Comment by OR13** [comment]
https://meta-guide.com/data/data-processing/automated-reasoning/json-rule-engines-2019

**Comment by OR13** [comment]
https://www.openpolicyagent.org/docs/latest/#expressions-logical-and

^ we have used this before... and its part of CNCF.... it has built in support for JWTs....

https://www.openpolicyagent.org/docs/latest/http-api-authorization/#8-optional-use-json-web-tokens-to-communicate-policy-data

Roadmap for JSON Schema support:

https://github.com/open-policy-agent/opa/issues/1449

Downside is it relies on a DSL "Rego"... upside is that it has lots of other supporters... who don't care about VCs... and its not a new thing...

**Comment by OR13** [comment]
Example, from Dapr explaining why OPA is a thing:
https://github.com/dapr/dapr/issues/1617

**Comment by OR13** [comment]
https://github.com/open-policy-agent/opa

**Comment by csuwildcat** [comment]
Resolved, with prejudice.
