### ISSUE TITLE
Suggestion - making presentation_submission optional

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#229]
The concept of making presentation_submission works well for navigation within a single JSON object, but becomes problematic with protocols that allow claims to be returned via multiple artifacts, allowing only .

Some transport protocols, like OpenID Connect can return claims in multiple artifacts - ID Token in the response; UserInfo Response from a separate endpoint called user_info endpoint; and vp token that can be used to return only VP.
- ID Token: https://openid.net/specs/openid-connect-core-1_0.html#IDToken
- UserInfo: https://openid.net/specs/openid-connect-core-1_0.html#UserInfo
- VP Token: https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0.html#name-vp-token

Having presentation_submission would confuse presenters of the claims (OpenID Providers), since it's has been up to them to decide where to return and organize presentations. 

I understand that some protocols need presentation_submission, and this is a breaking change, so am open to options other than making it optional.

**Comment by csuwildcat** [comment]
I want to note something that folks may not realize: you can put `presentation_submission` objects in basically any place, including the three listed above. (as far as I can tell)

**Comment by tlodderstedt** [comment]
Let's assume a OpenID Connect RP obtains an ID Token, a VP Token and an Userinfo response in the same flow. What is the value of having a presentation_submission in every of those objects? I would see some value, if the presentation submission would be part of the ID token, which would refer to presentations in the different objects (like a dictionary).

**Comment by OR13** [comment]
I agree with @csuwildcat folks are welcome to rebuild `presentation_submission` from transport specific intermediate representations... thats none of this specs business. You do need to form a normatively conformant data model, to conform to the spec at the end of that process.

**Comment by csuwildcat** [comment]
Joint group has agreed to keep the PE Submission, just need to settle on where it goes. We'd like to close this in favor of the Issue tracking where it goes in the OIDC repo.
