### ISSUE TITLE
Do Presentation Definition objects need a nonce?

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#23]
Nonces are great to use in protocols when brokering a new message exchange so that we can protect against attacks such as replay attacks.

If we were to include a nonce in the Presentation Definition, then it would allow Presentation Submissions to be tied to a specific "transaction" of Presentation Exchange, and this eliminates many classes of attacks.

However, if we were to require a nonce, then we will change the scope of Presentation Exchange in that it would no longer be a "static copy of a form" that anyone could use, but rather it would need to be coupled with a suitable PRNG to "stamp" each copy of the form with a nonce.

@dhh1128 is this an accurate portrayal of the issue? Thanks.

Ideas (not necessary mutex):
1. Require a nonce in the Presentation Definition
2. Make a nonce optional in the Presentation Definition
3. Allow for user-submitted nonces in the Presentation Submission, e.g., submit a "nonce" in the format of "{{pubkey}}-{{ISO-datetime}}", with the server checking that the "nonce" is within 30s of its current time.

re: https://github.com/decentralized-identity/presentation-exchange/pull/18/files/eba6f3f9b1ae7f27beaceea5c9a6bc66e5fc1980#diff-9308a2575ae14de31b25f4459ecfc604R53

**Comment by wyc** [comment]
We will probably do 2

**Comment by dhh1128** [comment]
Yes, you have captured my concern accurately.

I recommend a 4th option: Distinguish between a presentation *definition* and a presentation *request*. A definition is abstract and never directly replied to; thus, it never needs a nonce. A presentation *request* is a definition plus a nonce, and is always what provers respond to.

**Comment by wyc** [comment]
I think that's a very simple way to enable the optionality and separate concerns between the instance-pinned Presentation Request and the static Presentation Definition.

Any thoughts? cc @rado0x54 @csuwildcat
