### ISSUE TITLE
Suggestion: Submission Requirements should have a required `id` field

### ISSUE THREAD

**Issue by JaceHensley** [decentralized-identity/presentation-exchange#235]
I think it would be nice to have a required `id` on Submission Requirements. Mainly for when the submitted Presentation Submission is tested against the corresponding Presentation Definition. Currently you have to keep track of the whole SR object if you want to know which SR was not satisfied by the PS, instead it would be nice to just have to keep track of the SR's id.

**Comment by csuwildcat** [comment]
Per convo with Jace we can close this in favor of using existing structure/pointers.
