### ISSUE TITLE
Editorial issues cont'd

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/presentation-exchange#253]
Breaking out remaining issues from #245

| Line no | Type | Suggestion | 
|------- | ----- | ------------|
| 84      | Clarification | DID (and VC definitions) do not link to w3c specs. This is likely intentional but could be confusing as the audience will have a mix of understanding of the specs / context. Should we refer to the specs as informative? Do we need to clarify definitions are broader?
| 137, 187 | Clarification | "Presentation Definitions are objects that articulate what proofs a Verifier requires." > "...what ^claims/credentials^ and proofs" |

Recommendation from previous WG call (line 84)
-  agreed, plus consider case-by-case where/how things are used
- search "ref:" for ease of finding

**Comment by JaceHensley** [comment]
closed #332
