### ISSUE TITLE
Missing JSON-LD vocabulary for presentation-submissions

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/presentation-exchange#26]
I cannot find the JSON-LD context `https://identity.foundation/presentation-exchange/submission/v1` included in the presentation_submission examples where "PresentationSubmission" must be defined.

**Comment by csuwildcat** [comment]
@OR13 can you provide an update or PR to satisfy this?

**Comment by OR13** [comment]
@csuwildcat I think it would actually better for someone else to learn how to do this... 

Please assign someone else, I am happy to review their work.

**Comment by llorllale** [comment]
@csuwildcat @OR13 status on this one?

**Comment by OR13** [comment]
@llorllale someone other than myself should construct a JSON-LD context for this spec... it would be great practice... here is an example:

The magic of JSON-LD requires developers to understand how to construct valid URLs and put them in a JSON file...

its hard, but here is an example:

https://github.com/w3c-ccg/security-vocab/blob/master/contexts/security-v2.jsonld#L13
https://github.com/w3c-ccg/security-vocab/blob/master/contexts/security-v1.jsonld#L7
https://w3id.org/security#
https://w3id.org/security#verificationMethod -> redirect to ->
https://w3c-ccg.github.io/security-vocab/#verificationMethod

in this way, vocabulary terms used can have their definitions updated... Its actually the exact same approach taken by https://www.iana.org/assignments/jose/jose.xhtml

just represented in JSON not HTML.

**Comment by brentzundel** [comment]
@llorllale do you think you might be willing to submit a PR that addresses this? As @OR13 has said, it may be a valuable learning experience.

**Comment by csuwildcat** [comment]
@llorllale @OR13 we're going to put this on the agenda next week, so would you be able to come on and talk through it?

**Comment by OR13** [comment]
Not sure, ping me when its closer...

Here is a complete example of how to set this up nicely:

https://github.com/w3c-ccg/universal-wallet-interop-spec/blob/master/docs/contexts/wallet-v1.json

https://github.com/perma-id/w3id.org/pull/1853

**Comment by csuwildcat** [comment]
> Not sure, ping me when its closer...

@OR13 it's closer.

**Comment by glcohen** [comment]
@OR13 will not give a class at IIW. @csuwildcat will try his darndest.

**Comment by OR13** [comment]
@csuwildcat looking forward to reviewing your PR, I believe in you.

**Comment by JaceHensley** [comment]
I made a temporary context (to be used inline as an stopgap solution) if anyone is interested:

```
{
  "@version": 1.1,
  "PresentationSubmission": {
    "@id": "https://identity.foundation/presentation-exchange/#presentation-submissions",
    "@context": {
      "@version": 1.1,
      "presentation_submission": {
        "@id": "https://identity.foundation/presentation-exchange/#presentation-submissions",
        "@type": "@json"
      }
    }
  }
}
```

**Comment by OR13** [comment]
@JaceHensley thanks! @csuwildcat this what you were trying to figure out how to do!

**Comment by glcohen** [comment]
@JaceHensley @OR13 is that good enough to commit & close this?

**Comment by OR13** [comment]
ideally you would write some tests that showed that it worked as well, but yes, i think it will work.

**Comment by csuwildcat** [comment]
This is now added as a file and resolving at the prescribed URL

**Comment by OR13** [comment]
https://identity.foundation/presentation-exchange/submission/v1
