### ISSUE TITLE
`pattern` property not defined

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#270]
What is the `pattern` property used in constraints.types without being defined?

>  "constraints": {
          "types": [
            {
              "path": ["$.credentialSchema.id", "$.vc.credentialSchema.id"],
              "filter": {
                "type": "string",
                "pattern": "https://bank-schemas.org/1.0.0/accounts.json|https://bank-schemas.org/2.0.0/accounts.json"
              }
            }
          ],

**Comment by csuwildcat** [comment]
The `filter` prop is a JSON Schema object, all of the properties for which are defined by JSON Schema: https://json-schema.org/draft/2020-12/json-schema-core.html
