### ISSUE TITLE
Remove superfluous `types` property in constraints

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/presentation-exchange#272]
David Chadwick raised the issue that we only need `fields`, not `types`, so his proposal is to remove `types` and add 0-index iteration language to `fields`, simplifying the spec. Folks in DIF were previously a fan of this before types was put into spec text, so there would be agreement if the OIDC crowd was of the same mind as David. CCing @tlodderstedt for visibility.

**Comment by tlodderstedt** [comment]
Thanks for the notification. 

Does it mean type requirements are expressed as field constraint over whatever field holds type information in a certain credential format?
Is there a text proposal on the table?

**Comment by David-Chadwick** [comment]
@tlodderstedt Yes this is the intention. Also that RPs would make type searching the first fields constraint in their request, so that it is evaluated first by the wallet.

**Comment by tlodderstedt** [comment]
That's a reasonable change given that the rest of the input descriptor refers to the actual credential's structure as a JSON object (with different paths for JWT and LD Proofs, for example). Since we have the format now in the input descriptor, the verifier can also clearly state the expected format and type.

**Comment by csuwildcat** [comment]
@OR13 @JaceHensley @brentzundel any thinking here? Frag `types` in favor of using the single area for value interrogation? (I think we had wanted it this way before, so I am supportive of this simplification)

**Comment by JaceHensley** [comment]
I'm fine with this. There were some people who wanted the separate `types` property for semantic purposes, I forget exactly who wanted that tho

**Comment by csuwildcat** [comment]
Done in latest PR: https://github.com/decentralized-identity/presentation-exchange/commit/901937b12d80832f283b0f4d5bdae8df24bceb60

**Comment by bumblefudge** [comment]
Note, spec language was also changed by a [loose commit](https://github.com/decentralized-identity/presentation-exchange/commit/b05c5dc98a905bcb6d8ba95cd961879bf31441ad) that was probably intended for the PR above.
