### ISSUE TITLE
Any thoughts on JSON path node implementations to fit for this?

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/presentation-exchange#274]
I found 

https://www.npmjs.com/package/jsonpath-plus
&&
https://www.npmjs.com/package/jsonpath

Chose the plus version, but should this make any recommendations?

**Comment by csuwildcat** [comment]
@vongohren we have implementations listed in the spec.

**Comment by vongohren** [comment]
@csuwildcat i serach for implementations and did not find ut :S That is why i raised this question. But I will look again!

**Comment by csuwildcat** [comment]
@vongohren here's the link to the appendix section: https://identity.foundation/presentation-exchange/#jsonpath

**Comment by JaceHensley** [comment]
I've used jsonpath-plus before, I like that it ships it's own TS types
