### ISSUE TITLE
Demonstrate proof of link secret constraints for fields

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/presentation-exchange#28]
In reference to #24 

We must support the specification of a proof of link secret constraint as expressed as a base64 encoded data field. The contents are not necessarily known ex-ante in their entirety or sometimes at all. Instead, implementation-specific algorithms must be ran to ensure their integrity and validity.

**Comment by brentzundel** [comment]
this issue has broadened somewhat. The work to complete is a generalization of the holder binding proof to include: 
1. proof of control of a DID embedded in the credential
1. proof of knowledge of a link secret in a credential
1. proof of biometric bound to a credential (this may possibly be further broadened to include holder binding via some other credential)

**Comment by csuwildcat** [comment]
@brentzundel please update the status of this when you have time, we're wondering what to do with it, as it's marked as a version finalization blocker.
