### ISSUE TITLE
Enabling 'on the fly' collection of credentials

### ISSUE THREAD

**Issue by RieksJ** [decentralized-identity/presentation-exchange#284]
Constructing an input descriptor is only useful if the party that constructs it is certain that a holder can actually satisfy it. Thus, verifiers will have made sure that the (kinds of) credentials from which input is requested will actually be issued by parties that it trusts. It is reasonable to assume that a verifier may have found out at which endpoint (URI) an issuer is actually issuing the credential. Embedding the URI where a (designated) issuer will be issuing such credentials into an input descriptor enables the holder to request that credential if it did not already have it in its wallet, and it relieves him of the task of finding out where it would need to go to collect that credential otherwise.

**Comment by csuwildcat** [comment]
Instead of including random URLs into PE, we should focus on finalizing the Identity Hub spec, because that way you can just assemble/locate lists of DIDs for Issuers and the mechanism for contacting them for issuance is automatic: you resolve their DIDs, find their Hub endpoints, and initiate an issuance flow.

**Comment by RieksJ** [comment]
I'm not religious about the way in which 'on the fly' collection of credentials can be done, as long as it can be done. 

Not being in a position that I can follow everything that's going on I proposed the simple URI solution, which btw is not just a 'random' URL, but something that would actually serve a very useful purpose, doesn't rely on specifications that are still under development, and is easier to use for contacting issuers for automatic issuance. But as I said, I'm good with hubs if they serve that purpose.

**Comment by csuwildcat** [comment]
When I said "random URLs" I just meant adding more brittle pointers to the exchange that would require their own spec to define what issuance protocol they represent/offer, which we can 'get for free' if we circle the wagons around Hubs.
