### ISSUE TITLE
Need editorial pass to ensure interpretation of Features is clear

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/presentation-exchange#299]
- Need a better description of feature behavior, i.e., "light up" if features understood, backwards compatible
- Need language around processing entity handling when Features not supported, reflecting the "naughty behavior" discussion. @csuwildcat

**Comment by dtmcg** [comment]
@kimdhamilton is this sill relevant ?

**Comment by kimdhamilton** [comment]
Shall we close this? I don't think it's pressing.
