### ISSUE TITLE
What existing presentation definition implementations are there?

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#3]
Please add as comments links to existing proof requests and presentation definitions so we can get an idea of what folks have already done. This will help us to both try to make our presentation definition work with existing implementations and help us avoid redoing work that has already been done

**Comment by rado0x54** [comment]
Civic / Identity.com: https://github.com/identity-com/dsr

**Comment by rado0x54** [comment]
Workday Proposal: https://github.com/decentralized-identity/presentation-request/blob/master/proposals/presentation-message-format.md

**Comment by rado0x54** [comment]
Bloom: https://github.com/hellobloom/attestations-es/tree/master/packages/share-kit

**Comment by David-Chadwick** [comment]
Our system allows the Verifier to specify a tree of policies in DNF or CNF. This allows a verifier to specify any conceivable combination of VCs that the Holder must present in order to gain access to the Verifier's resources

**Comment by OR13** [comment]
Are these added to the appendix? I think UPort has one now as well...paging @awoie.

**Comment by csuwildcat** [comment]
Please continue adding if you have work that you want others to view and reference as we develop the spec.
