### ISSUE TITLE
Double-check Input Evaluation section

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/presentation-exchange#300]
Double-check "Input Evaluation" section. Some specific questions:
- Our existing description of limit_disclosure was confusing, and now also needs to capture the "wallet doesn't understand" case. The latter is described in Input Descriptors, but needs to be updated here too
- Why do we have "Expired and Revoked Data" as separate sections rather than steps in Input Eval?

**Comment by dtmcg** [comment]
@kimdhamilton is this still relevant ?

**Comment by csuwildcat** [comment]
Closing, but if folks still see an issue, feel free to reopen.
