### ISSUE TITLE
Matching on arrays of strings

### ISSUE THREAD

**Issue by David-Chadwick** [decentralized-identity/presentation-exchange#303]
If a VC contains a property whose values are a set of strings, e.g.

foo = ["bar", "baz"]

then a presentation definition filter will need to specify one-of or any-of from the array of values e.g.

	"path": [
		"$.foo"
	],
	"filter": {
		"type": "array",
		"items": {
			"type": "string"
		},
		"oneOf": ["foo", "abc"]
	}

Unfortunately when the above PD has been entered into the OIDC4VP draft, there is a schema checking violation on the oneOf property (also anyOf gives a similar error). The authors of OIDC4VP feel that this is a problem with the PE specification, in that it is not precise enough about which schema validation rules (year, version) have to be used. Nor is there any indication of which tools exist in order to validate that any PD instance is a correct instance of the PE specification.

**Comment by csuwildcat** [comment]
I believe your filter would look like this:

```json
{
  "type": "array",
  "items": {
    "anyOf": [
        {
          "type" : "string",
          "pattern" : "foo|abc"
        }
     ]
   }
}
```

**Comment by JaceHensley** [comment]
Here's the docs for handling tuples with json schema https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

**Comment by csuwildcat** [comment]
Closing as complete, given the requested filter is supported and examples have been provided.

**Comment by Sakurann** [comment]
why was this closed complete? json schema validation for oid4vp example still fails, no?

**Comment by JaceHensley** [comment]
I believe this was closed because json schema supports the requested filter. There's nothing PE specific about the json schema capabilities

**Comment by kimdhamilton** [comment]
Reopening per #480

**Comment by decentralgabe** [comment]
this should be addressed by specifying Draft 7 here https://github.com/decentralized-identity/presentation-exchange/pull/481

closing this now, please re-open if this solution is insufficient
