### ISSUE TITLE
Editorial: ensure samples are clear when mixing decoded credentials

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/presentation-exchange#305]
Note to self: sometimes we mix decoded forms of credentials and it's unclear to implementors. Ensure we clean up

**Comment by dtmcg** [comment]
note to @kimdhamilton does this require action ?

**Comment by kimdhamilton** [comment]
Confirmed relevant samples are confined to the appendix and are appropriately documented; e.g., https://identity.foundation/presentation-exchange/#presentation-submissions
