### ISSUE TITLE
Presentation Submission needs a JSON Schema

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/presentation-exchange#313]
All other types have a schema!

**Comment by brentzundel** [comment]
The spec says that the JSON schema is
> for evaluation of the portions of the Presentation Exchange specification that call for JSON Schema validation

Which might explain why it was never included for `presentation submission`

**Comment by brentzundel** [comment]
which is not an argument against including it, just a fun fact.

**Comment by decentralgabe** [comment]
I will follow up with a a PR for a schema.

**Comment by decentralgabe** [comment]
looks like there is one, just needs to be added to the spec https://github.com/decentralized-identity/presentation-exchange/blob/master/test/presentation-submission/schema.json

**Comment by decentralgabe** [comment]
https://github.com/decentralized-identity/presentation-exchange/pull/327
