### ISSUE TITLE
Typo when referring to input_descriptors

### ISSUE THREAD

**Issue by pamelatech** [decentralized-identity/presentation-exchange#33]
In section 4,  this sentence is problematic:
> If no submission_requirement is present, all inputs listed in the input_descriptor array are required for submission

The element called "input_descriptor" is an object.  The element called "input_descriptors" is an array.   Therefore the sentence listed above should be corrected to refer to the array in question as the "input descriptors array".

**Comment by csuwildcat** [comment]
Closed via merge of https://github.com/decentralized-identity/presentation-exchange/pull/83
