### ISSUE TITLE
Missing Generic Vocabulary for Transport Request/Response

### ISSUE THREAD

**Issue by pamelatech** [decentralized-identity/presentation-exchange#34]
As written today the presentation exchange draft is confusing to read - it is supposed to be a spec defining a data format, but there are transport details all over the place.  The examples are hard to read if you are used to a different transport and it is difficult to understand where the line is between presentation exchange and all the rest. 

If you were to create a generic name for the out-of-scope request/response that the presentation def/sub objects are embedded in, then you could remove the transport details from any examples that aren't explicitly intended to explain how a specific transport affects the objects.

I recommend the terms "information request" and "information response".   Any of the transports already documented could fall under this term, and it works equally for authentication requests, authorization requests, attribute exchange requests or credential presentations.   I have included an example high-level diagram which might help new readers understand where the defined objects are placed in relation to verifiers, holders, requests and responses before they dig into the data format itself.

![exch-overview](https://user-images.githubusercontent.com/2591320/86533351-6c973c80-be85-11ea-8b4b-41242cfca856.png)

**Comment by brentzundel** [comment]
@pamelatech, PR #81 added a section about a `presentation request` envelope for `presentation definitions`.
Does that resolve this issue to your satisfaction, or would you prefer `presentation request` be changed to `information request`?
