### ISSUE TITLE
Duplicate definitions of Input Descriptors

### ISSUE THREAD

**Issue by colbyharrison** [decentralized-identity/presentation-exchange#346]
Input Descriptor is defined in two locations. Partially in Section 5.0 and fully in section 5.1.  The partial definition in section 5.0 is inaccurate as it states the below inputs are `required` while only listing a partial list of inputs that `MAY` be included.  

Can we cleanup section 5.0 to remove the partial definition of Input Descriptors?

**Comment by nklomp** [comment]
Could you point to the exact line(s) in 5.0 that according to you are invalid? I do not see it on first glance. I am assuming you are talking about the last line in the below quote.

> input_descriptors - The [Presentation Definition](https://identity.foundation/presentation-exchange/#term:presentation-definition) MUST contain an input_descriptors property. Its value MUST be an array of [Input Descriptor Objects](https://identity.foundation/presentation-exchange/#term:input-descriptor-objects), the composition of which are described in the [Input Descriptors](https://identity.foundation/presentation-exchange/#input-descriptors) section below.
> 
> All inputs listed in the input_descriptors array are required for submission, unless otherwise specified by a [Feature](https://identity.foundation/presentation-exchange/#term:feature).

The intent of that line seems to be not about any properties from an input_descriptor object to be mandatory, bot more that all input descriptors present, should be satisfied. The above text is IMO not really a definition of input_descriptors, but more an indication that it is an array of objects explained in 5.1

I guess the last line could be made more clear, but I also believe it to be factualy correct.

So the question is, do you mean that last line or is there something I am overlooking?

**Comment by colbyharrison** [comment]
After looking at this again. I now understand the intention. I mistakenly took the `name`, `purpose`, `format` properties underneath the `All inputs listed in the input_descriptors array are required for submission, unless otherwise specified by a [Feature](https://identity.foundation/presentation-exchange/#term:feature).` line as referring to the `name`, `purpose`, `format` properties of Input Descriptors instead of Presentation Definition. Closing as this does not require any changes.
