### ISSUE TITLE
Terminology matters: Use names that help readers build the right mental model

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/presentation-exchange#35]
The specification sometimes uses the term “Verifiable Credentials” when what’s meant is verified/verifiable claims that may or may not be in W3C Verifiable Credentials format.  That terminology usage will cause endless and unnecessary confusion.  We owe it to those reading our specs and those we interact with to use terminology that brings clarity and understanding and guide them towards doing the same.

No matter how we might intended it to be heard, the term “Verifiable Credentials” will essentially always make people think we’re talking about the W3C Verifiable Credentials data structure.  So that’s not a workable term for the generic concept of verified claims.

On a call, Daniel suggest simply “Credentials”.  The problem with that is that “Credentials” already has a meaning in the identity/security community, in which things like passwords, smart cards, OTPs, PINs, etc. are credentials.  (Along these lines, W3C has a Credential Management spec https://www.w3.org/TR/credential-management-1/ and WebAuthn https://w3c.github.io/webauthn/ is an API for “Public Key Credentials”.)

I could live with any of these terms for the generic concept:
•	Verified Claims (already in widespread use)
•	Verifiable Claims
•	Verified Assertions (borrowing from SAML terminology)
•	Verifiable Assertions

Let’s discuss among ourselves which we prefer.  But please, let’s apply our editing skills and tact to steer people towards using accurate language.

Terminology matters.

**Comment by csuwildcat** [comment]
Need to define credentials in the Terminology section, bike shedding begin!

**Comment by selfissued** [comment]
The labels are referenced in the examples in statements like `"from": "B"`, where in this example, the label is `B`.

**Comment by glcohen** [comment]
Will be handled in #90

**Comment by glcohen** [comment]
label reference https://github.com/decentralized-identity/presentation-exchange/issues/37

**Comment by csuwildcat** [comment]
PROPOSAL: Use `Claim` as the term that encompass all things credentials, JWTs, tokens, etc.
