### ISSUE TITLE
Input Evaluation does not cover the case where constraints are empty

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/presentation-exchange#361]
https://identity.foundation/presentation-exchange/#input-evaluation

According to the data model, a Presentation Definition's Input Descriptors [may contain a constraints property](https://identity.foundation/presentation-exchange/#input-descriptor). This means that there are Input Descriptors without constraints.

Language is missing on how to process such Input Descriptors, which I imagine should satisfy a given format requirement, if present.

**Comment by brentzundel** [comment]
This makes me wonder if an Input Descriptor without a constraints property makes any sense. What does an Input Descriptor that contists of only an Id field even mean?
In v1.0.0 the input descriptors would at least contain a schema property, so there was something to filter against on processing. Then we moved that to fields. . .

sounds like we've got a bug.

**Comment by decentralgabe** [comment]
I agree, I think Input Descriptors need to be a required field.

**Comment by bumblefudge** [comment]
Discussed on today's call: proposal was to make at least one constraint (any of the optional constraint types) mandatory
