### ISSUE TITLE
diff btw PE v1 and v2

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#363]
what are the differences between Presentation Exchange v1 and PE v2?
Would it be possible to add a section with bulletpoints enumerating major differences?

**Comment by bumblefudge** [comment]
precedent/paragon here:
https://didcomm.org/book/v2/whatsnew

**Comment by Sakurann** [comment]
? that's what's new in DIDComm v2, right?

**Comment by nklomp** [comment]
PR #369 Is ready for review. 

I still want to have a quick look at whether the optional, prefered, required changes of Features need to be mentioned
