### ISSUE TITLE
remove agenda files?

### ISSUE THREAD

**Issue by andorsk** [decentralized-identity/presentation-exchange#380]
Are the agenda files https://github.com/decentralized-identity/presentation-exchange/blob/main/agenda2021-1.md and https://github.com/decentralized-identity/presentation-exchange/blob/main/agenda2022-1.md relevant anymore? Can they be moved? As a newer contributor, it seems like these are out of date and red herrings considering they haven't been updated since 11 months ago.

**Comment by andorsk** [comment]
@csuwildcat @brentzundel any thoughts here?

**Comment by brentzundel** [comment]
maybe this is an indication that we should be trying harder to have an agenda . . .
or at least making sure notes are kept.

**Comment by andorsk** [comment]
😆 let's just bring this up the next CC call. The way I see it, there's kinda three options:

1. use them and maintain them
2. archive them ( in a subfolder or something )
3. delete them

**Comment by andorsk** [comment]
on DIF: intent is supposed to summarize the work. Helps DIF to write the newsletter. proposal: we have a note taker each meeting to jot minutes. possibly add higher level "initiatives" and "goals" in the agenda.

**Comment by andorsk** [comment]
@bumblefudge to get Dec 1 sample and we'll figure out a flow from there.

**Comment by dtmcg** [comment]
decision to update the files and keep track of them 
extra usefullness
