### ISSUE TITLE
If validation is out of scope, say so, and say how it happens

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/presentation-exchange#40]
The spec does not appear to validate the VCs or eKYC-IDA JWTs received.  If this is out of scope, please explicitly say so.  And if so, please say when and where things like signature and issuer validation are expected to happen when this spec is used.

**Comment by csuwildcat** [comment]
Closed via merge of https://github.com/decentralized-identity/presentation-exchange/pull/83
