### ISSUE TITLE
description of the format property should be paraphrased for clarity.

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#413]
`If present, its value MUST be an object with one or more properties matching the registered [Claim Format Designations](https://identity.foundation/presentation-exchange/#claim-format-designations)` this text is not clear.

Could you please clarify that `it is an object containing a list of key value pairs, where the key is XXX and the value is XXX.`

**Comment by csuwildcat** [comment]
Change to language has been merged.
