### ISSUE TITLE
input descriptor object with no fields?

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#429]
currently the input descriptor object must contain a constraints object with one of a fields object or a limit_disclosure object.
Is there a use case for a presentation definition that only has a limit_disclosure object and no fields?
or should this language be updated to make the fields object a MUST?

See https://identity.foundation/presentation-exchange/spec/v2.0.0/#input-descriptor-object

**Comment by andorsk** [comment]
Discussed on DIF call: 

Reasonable point of clarification. Might need some refactoring or different verbiage. There's a few different ways to handle this. 

Should try to revisit this by the next milestone. 

May shift to `Future` as we discuss further. Anchoring to milestone `2.1` for now, just to keep things anchored and make sure this is addressed in a reasonable timeframe.

**Comment by brentzundel** [comment]
since even the type and issuer are represented by fields, it seems that even to show ownership of a certain type of credential without revealing the personal data would still require at least one field. Meeting on 8/24 recommends clarifying that you need at least one field, or at least clarifying the language.

**Comment by csuwildcat** [comment]
Wording adjusted in https://github.com/decentralized-identity/presentation-exchange/commit/50b335dc28468ac32ad2145bdec71662a20d4504
