### ISSUE TITLE
Make submission_requirement an array, not an object, rename to submission_requirements

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/presentation-exchange#43]
Making this an array will allow for both a singular pick capability and a flat series of group-based requirements.

**Comment by wyc** [comment]
Thanks, we discussed this on the basis that a flat series of multiple requirements would be the most common use case as opposed to a single requirement. No objections from me and sounds reasonable.

**Comment by csuwildcat** [comment]
This is probably a more appropriate Issue to flesh out the final requirements revision. Assuming you separate the uses of `from` to remove the polymorphism, you can turn on logic using the separate props via a fall through, just like the current [code example](https://codesandbox.io/s/gallant-bartik-cu8ns?file=/src/selection_evaluation.js) does for evaluating count, minimum, and maximum. I also noticed that there is currently no way to pick X number of inputs across more than one group, so that's possible by simply making the from/input group selection prop an array of group strings.

I have done the following in the example below:

1. Removed the polymorphism of `from`, splitting into two props
2. Without any numeric pick/threshold directives, `from` = "all of these things"
3. Removed rules altogether
4. Made `from` (which selects all or N inputs of a group) an array, to select N across groups.
5. Reused the word `pick` to just mean pick exactly N of the following targets
6. Changed `minimum` and `maximum` to just `min` and `max`

```javascript
  "submission_requirements": [
    { "pick": 1, "from": ["A", "B"] },
    {
      "pick": 1,
      "from_nested": [
        { "from": ["C"] },
        { "pick": 1, "from": ["B", "D"] },
        { "min": 2, "max": 4, "from": ["D", "E"] }
      ]
    }
  ]
```

**Comment by csuwildcat** [comment]
We could also consider renaming `from_nested` to `requirements`, which denotes nesting and is a bit more specific about what you're actually picking.

**Comment by wyc** [comment]
@csuwildcat I like that you kept polymorphism out of everything. This syntax makes sense to me, and two thoughts that would move it towards resolution for me:

1. I see a problem with relying on checking existence of chords of property names to delineate the type of rule being checked. This could result in a nightmare where we must be very careful that property names are never re-used in different rules, and the behavior will be undefined (unless we added clarifying language) if end users stick multiple properties that could allow a submission requirement to be interpreted by multiple rules, which they probably will. Therefore, I recommend bringing back the rules to make it easier for implementors and to make the rule types explicit as opposed to reading the tea leaves of the present properties.

2. Can you give some examples of choosing from multiple input groups where we can't just put those same input fields under another group in addition to their existing ones? To me, they seem to be logically equivalent and would reduce the burden of the implementor for processing a submission request.

**Comment by csuwildcat** [comment]
1. No problem bringing back rules, just figured I would see what people thought. The rule thing makes it very explicit in the 'all' case, and the code hit is literally like 1 line, so np.

2. I am not sure what you are describing in this question. The case I figured we would make possible is one where a Verifier wants to require that a submitting party supply 2 inputs across groups A and B, but doesn't care about specific distribution. I didn't see an easy way to do that with the existing syntax, but perhaps there is, or you are talking about something else?

**Comment by csuwildcat** [comment]
Modified example to bring back rule-based logic delineation: 

```javascript
"submission_requirements": [
    { "rule": "pick", "count": 1 "from": ["A", "B"] },
    {
      "rule": "pick",
      "count": 1
      "from_nested": [
        { "rule": "all", "from": ["C"] },
        { "rule": "pick", "count": 1, "from": ["B", "D"] },
        { "rule": "pick", "min": 2, "max": 4, "from": ["D", "E"] }
      ]
    }
]
```

**Comment by glcohen** [comment]
Great amendment. Only q is will we allow nested inside nested a la
```
{
  "submission_requirements": [
    {
      "rule": "pick",
      "count": 1,
      "from": ["A","B"]
    },
    {
      "rule": "pick",
      "count": 1,
      "from_nested": [
        {
          "rule": "all",
          "from_nested": [
            {
              "rule": "pick",
              "count": 1,
              "from": ["A", "B"]
            },
            {
              "rule": "pick",
              "count": 1,
              "from": ["B", "C"]
            }
          ]
        },
        {
          "rule": "pick",
          "count": 1,
          "from": ["B","D"]
        },
        {
          "rule": "pick",
          "min": 2,
          "max": 4,
          "from": ["D","E"]
        }
      ]
    }
  ]
}
```

**Comment by glcohen** [comment]
Also, @wyc, I echo your sentiments about variable scoping, undefined, and poorly constructed rules. I think, generally, the syntax should be flexible to support all/majority combinations and tooling at a higher level should be built to prevent users from blasting their toes off.

**Comment by csuwildcat** [comment]
Yes, the intent is to allow N-depth nesting, which that reference JS code handles, and I will ensure works after we do the spec updates to add what we have discussed above.

**Comment by wyc** [comment]
@csuwildcat 
> 2. I am not sure what you are describing in this question. The case I figured we would make possible is one where a Verifier wants to require that a submitting party supply 2 inputs across groups A and B, but doesn't care about specific distribution. I didn't see an easy way to do that with the existing syntax, but perhaps there is, or you are talking about something else?

My proposed solution for this use case is to ensure that input descriptors in groups N_1, N_2, ..., N_m are also each in group T. We already allow a single input to exist in multiple input groups, so adding "another way to do it" feels superfluous to me if we can't identify meaningful use cases that can't already be covered. Specifically, you would change something like:
```
"group": ["N_1"],
```
to
```
"group": ["N_1", "T"],
```
in the Input Descriptor, then just pick from `T`.

**Comment by wyc** [comment]
i think by allowing multiple groups into submission requirement, it is actually a footgun
10:21
to me, it's harder to reason about pick 3 from Driver's License, Utility Bills, and Proof of Income
10:22
{
  "rule": "pick",
  "count": 3,
  "from": ["DriversLicense", "UtilityBill", "ProofOfIncome"]
}
10:22
what does that mean to someone who just looks at it?
10:22
because technically it means that 3 utility bills may satisfy this requirement

**Comment by wyc** [comment]
I think this was merged, as per the latest spec on master: https://github.com/decentralized-identity/presentation-exchange/blob/12fcdb694c1e95b88124aa735f5bfedc73e9631d/spec/spec.md#submission-requirements
via
https://github.com/decentralized-identity/presentation-exchange/commit/31c5e11941b20bb95f480df476bf264965b4fe36

@csuwildcat can you confirm if this was the case, and if so, close this issue? Thanks!

**Comment by csuwildcat** [comment]
PR merged
