### ISSUE TITLE
Mixed-claim-format VP use case

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/presentation-exchange#431]
In a [comment](https://github.com/decentralized-identity/presentation-exchange/issues/412#issuecomment-1511980409) that almost got lost in the shuffle, @decentralgabe pointed out that the claim format section is moot on the subject of VPs comprised of VCs in different claim formats.  As this use-case is a crucial one to at least one implementer/editor, I have to wonder:

1.) do we need a use cases section making this explicit? if so, is that a v2.1 or a v3 decision?

2.) does the claim format section of the [5.1.1 input descriptor object](https://identity.foundation/presentation-exchange/spec/v2.0.0/#input-descriptor-object) as written need to explicitly mention VPs can contain multiple claim formats recursively? i.e., should it warn implementers that a VP containing VCs should be described by an input descriptor (constraining each possible VC) inside of an input descriptor (constraining the VP containers) to create two separate validation contexts?

3.) do any other sections stand to be edited/updated to reflect this use-case?  I noticed that in [section 6.3 validation of claims](https://identity.foundation/presentation-exchange/spec/v2.0.0/#validation-of-claims), there's a reference to validating ONE SIGNED/VERIFIABLE CONTAINER AT A TIME, which includes the example of a VP with one VC in it-- which implies that the VP signature defines one container for validation, but leaves a little ambiguous which container to consider when a VP contains two differently-signed (and thus separately trustworthy) containers!

**Comment by decentralgabe** [comment]
1. Yes, 2.1 - we need guidance now
2. I think it should explicitly mention VPs can contain multiple claim formats
3. probably some examples to show this

**Comment by bumblefudge** [comment]
Mentioned on today's call that OWF is polling implementations about this very use-case, which they are discussing actively.  mDoc/VC-mixed or SD-JWT/VC-JWT mixed VPs are being discussed.

**Comment by bumblefudge** [comment]
discussed on today's call: @dmitrizagidulin pointed out that multiple VCs in one VP were actually part of the interop profile structuring the Department of Ed plug-a-thon, documented here:
https://w3c-ccg.github.io/vc-ed/plugfest-3-2023/

(this could be used when adding a user stories section)

**Comment by bumblefudge** [comment]
closed by #444
