### ISSUE TITLE
support ZKP-style predicate requests and selective disclosure

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#46]
As raised in #18 

>          // TODO: how do you express zero-knowledge predicate requirements?

The presentation request should be able to request predicates (and specify the values against which credential values should be tested)

**Comment by csuwildcat** [comment]
The assumption is that this would either be done with JSON Schema `filter` interpretation, or as an additional property we add to the `field` entries objects that defines a syntax for doing so. (I would prefer the former, if possible)

**Comment by swcurran** [comment]
I think selective disclosure should be removed from the title of this issue, as I think the spec. is pretty clear on how selective disclosure is requested.

It feels like adding something to the filter to indicate a ZKP predicate would work, but I'm not sure what it would look like in the general case. Would the signature have to be specified to indicate would types of ZKP predicates are allowed?  Fallback would have to be disclosure of the value.
