### ISSUE TITLE
Link to Incorrect Anchor

### ISSUE THREAD

**Issue by Ennovate-com** [decentralized-identity/presentation-exchange#461]
In [Relational Constraint Feature](https://identity.foundation/presentation-exchange/spec/v2.0.0/#relational-constraint-feature) where it says 

> For more information about techniques used to prove binding to a [Holder](https://identity.foundation/presentation-exchange/spec/v2.0.0/#term:holder), please see [Holder Binding](https://identity.foundation/presentation-exchange/spec/v2.0.0/#holder-binding).

the fragment `#holder-binding` should be `#holder-and-subject-binding`

**Comment by rado0x54** [comment]
Thanks for bringing that up. Will be addressed.
