### ISSUE TITLE
Broken link in Submission Requirement

### ISSUE THREAD

**Issue by colbyharrison** [decentralized-identity/presentation-exchange#464]
Broken reference to Input Descriptor in this section https://identity.foundation/presentation-exchange/#submission-requirements 
<img width="880" alt="Screenshot 2023-12-21 at 10 14 17 AM" src="https://github.com/decentralized-identity/presentation-exchange/assets/11632011/a7f9c758-b084-467d-8c46-c3a1e189bc8d">

<img width="912" alt="Screenshot 2023-12-21 at 10 22 50 AM" src="https://github.com/decentralized-identity/presentation-exchange/assets/11632011/295bfb69-1eec-4ebf-82f7-5e4ca5283e92">

When describing how the `from` key works example 2 does not match with its description text 
```
In the second example, the [Submission Requirement](https://identity.foundation/presentation-exchange/#term:submission-requirement) requests from 2 to 4 inputs from [Input Descriptor](https://identity.foundation/presentation-exchange/#term:input-descriptor) group "B".
```
Either the example needs to be updated to include `max` or the description should state "2 or more inputs".

**Comment by colbyharrison** [comment]
and another ...
<img width="912" alt="Screenshot 2023-12-21 at 10 22 50 AM" src="https://github.com/decentralized-identity/presentation-exchange/assets/11632011/d9c1825b-7a03-4c24-821f-b425256c2577">

**Comment by rado0x54** [comment]
Thanks for reporting this. Will assign it to me and fix.
