### ISSUE TITLE
how to allow verifiers to require multiple credential inputs to be about same subject

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#47]
As raised in #18 

>    // TODO: how do you require that banking input 1 and banking
>    // input 2 both have the same credential subject (e.g., same
>    // primary account holder)?

If values from two different credentials are requested, the verifier should be able to specify that the attributes must have the same credential subject, or to specify the credential subject for each requested attribute.

**Comment by csuwildcat** [comment]
If these fields were populated in the credential, you would add a field filters that specified the same subject ID as the target. If proof of this required any orthogonal verification process beyond simply setting a field filter for comparison, I would say it's out of scope.

**Comment by swcurran** [comment]
I don't understand the line "you would add a field filters that specified the same subject ID as the target". Could you add more detail about what that means @csuwildcat ?

It would be nice for the verifier to be able to provide constraint expressions based on the claims to be included in the Presentation Submission so the holder did not respond to a request that would succeed cryptographically, but fail to meet the business need.  I'm guessing this would be too complicated, but would it be feasible to have a third top-level item that was a set of constraints applied to the Presentation Submission after it was assembled?  It would only be need to specify cross-credential constraints in the presentation submission such as Brent raises above -- e.g. an identifier in one credential (such as a name) matches an identifier in another credential being sent.

**Comment by csuwildcat** [comment]
Proposal: verify the spec clearly states the expected understanding of this concern

**Comment by csuwildcat** [comment]
Seems something like this would require a special meta-requirement set to be dynamically added to the Presentation Definition prior to handing it to the user, or in the case of ZKP, I am not sure if you could do the assessment based on the internal content of the credential at all. I think eval would be difficult to impose in a credential format agnostic way - for example, in the case of ZKPs: 'same subject' might only be something you can verify in the target format signature validation phase, by requiring the user to prove they are in control of different keys that are used to generate different ZKP credentials within the batch submitted.

**Comment by brentzundel** [comment]
This is related to issue #28 and will be addressed by the same PR that addresses that issue, imo

**Comment by csuwildcat** [comment]
@brentzundel  are we concluded for this line of Issues? If yes, just close this, if not, do we need further PRs for the 1.0 milestone?

**Comment by brentzundel** [comment]
PR #160 is ready for review.

**Comment by csuwildcat** [comment]
Latest PR accounts for this.
