### ISSUE TITLE
 allow requestor to specify that supplied attributes must be self-attested

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#49]
as raised in #18 

> TODO: Presumably a request for input that has no constraints is allowed to be self-attested -- but sometimes this isn't good enough. How do I say, "As a university verifying your study habits, I explicitly DON'T want an attestation from your high school guidance counselor; I want you to tell me what you think about yourself?"

**Comment by csuwildcat** [comment]
Proposal: allow a flag that the submission of an input must be self-attested.

**Comment by wyc** [comment]
Context/clarification from call:
* Self-attested means the subject and the issuer are the same.
* Holder-is-issuer means that the presenter of the credential and the issuer are the same.
* Holder-is-subject means that the presenter of the credential and the subject are the same.
