### ISSUE TITLE
Input Types: Raw Data

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/presentation-exchange#5]
An input type that's likely to be very useful, especially as we boot up a world of users who have no existing credentials, is one that describes a raw data field requirement. An input of this type should include considerations for the following:

1. Specifying what the data value must be (string, number, boolean, etc.)
2. Specifying limitations on the value (min/max length, valid ranges, etc.)
3. Associating the entry with a field ID or name

Here is a strawman example of what such a data type might look like inside a Proof Definition:

```json
{
  "type": "data",
  "field": "routing_number",
  "value": {
    "type": "string",
    "maxLength": 9
}
```

To address requirements 1 and 2 from the list above without reinventing the wheel, I propose that these things be specified via an existing standard: JSON Schema - https://json-schema.org/.

Please respond with your thoughts, and anything else you feel we should address in the scope of this input type.

**Comment by OR13** [comment]
IIRC, this is now supported @csuwildcat do we need an example or can this be closed?

**Comment by csuwildcat** [comment]
This can be closed now, given you can just use any schema, which could be a raw data schema of your choosing.
