### ISSUE TITLE
do we cover signatures on objects?

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#51]
as raised in #18 

> TODO: a demand for data should often be nonrepudiable and therefore must be signable by the Verifier. How do we do that?

Is there a specified way for the verifier to sign the presentation definition/request?

**Comment by csuwildcat** [comment]
That is not something the spec intended to cover, and was assumed to be part of the outer wrapper.

**Comment by glcohen** [comment]
Similar to #29 I believe this should be a part of the outer wrapper.

**Comment by csuwildcat** [comment]
Proposal: clarify in note that the outer envelop will handle signature validation
