### ISSUE TITLE
presentation definition sent via presentation request

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#52]
as raised in #18 

> TODO: I recommend that you draw a distinction between the definition of a presentation (here called a "presentation definition", very appropriately) and the request for such a presentation. It seems quite likely to me that presentation definitions will be standardized and published. For example, there might be a standard presentation definition that captures the requirements of people applying for citizenship in a given country. Once defined, the actual interactions where proofs are demanded need not define them again; they might just refer to them. Thus, it is possible to REQUEST a presentation without DEFINING it, by simply refering to a previously published DEFINITION. This is why the Aries protocol describes the challenge for proof as a "request", not a "definition" -- a request could include an inlined definition, or simply refer to one that's external to the request.

**Comment by csuwildcat** [comment]
This was the intent, that you could define these statically, dynamically, or refer to them by reference - can someone do a PR to clarify the language/guidance around this?

**Comment by csuwildcat** [comment]
Proposal: add language to the spec that details how the user of the spec should leverage existing envelops (OIDC, DIDComms, etc.) to facilitate presentation requests.

**Comment by csuwildcat** [comment]
This issue is an umbrella for https://github.com/decentralized-identity/presentation-exchange/issues/23

**Comment by csuwildcat** [comment]
https://github.com/decentralized-identity/presentation-exchange/issues/51

**Comment by brentzundel** [comment]
this is addressed in #81
