### ISSUE TITLE
localization support for text fields

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#53]
various property values are specified as strings (such as the `purpose` property). Should we introduce support for localization of these property values?

**Comment by csuwildcat** [comment]
I think this is a great idea, and our internal one-off MSFT data formats for exchanges features localization too. Can you articulate a possible solution for it?

**Comment by glcohen** [comment]
The [JSON Schema Spec has this to say](https://github.com/json-schema-org/json-schema-spec/wiki/Localization)...

I think we can add a `locale` property (e.g. "en-us") vis a vis [IETF BCP 47](https://tools.ietf.org/html/bcp47). This would allow interop with browsers/clients that can detect that, or link into HTTP `Content-Location` or `Accept-Language` headers. Other protocols likely have similar localization support.


what about adding a `locale` property?

**Comment by glcohen** [comment]
Done https://github.com/decentralized-identity/presentation-exchange/pull/75
