### ISSUE TITLE
JSON Path support

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#54]
the variant of JSONPath called for in the spec: https://www.npmjs.com/package/jsonpath
Is this variant supported outside of node.js?

**Comment by csuwildcat** [comment]
Yes, there are many other options listed here in the resources section of the spec: https://identity.foundation/presentation-exchange/#jsonpath

**Comment by csuwildcat** [comment]
Proposal: in the 4.2.5 section (https://identity.foundation/presentation-exchange/#input-descriptor-objects) don't point to Node.js version, point to the JSON Path grammar/implementation section.

**Comment by csuwildcat** [comment]
Addressed in update
