### ISSUE TITLE
input descriptor iteration algorithm

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#55]
as raised in #18 

> (TODO: unwind this advice to cease. A prover might have reasons to compute all the possible variations and pick the "best" one on the basis of which one is cheaper to present (has less fees associated), which one is more private, which credential they previously used with this verifier, etc. Stopping after the first match is not the business of the data format and is none of the verifier's business. Their requirements just way what is acceptable, not how it's computed.)

currently the algorithm for matching fields with input descriptors stops after the first match. Which field a prover wishes to select may be more nuanced than "pick the first one that matches"

**Comment by csuwildcat** [comment]
Proposal: add note with pseudo-example to show iteration of the credentials you hold.

**Comment by csuwildcat** [comment]
Addressed in PR
