### ISSUE TITLE
Count property to support range, rather than integer

### ISSUE THREAD

**Issue by jenniferwiner** [decentralized-identity/presentation-exchange#56]
When using the `"rule": "pick", "count": 1` properties, there may be a use case for having count be a range, rather an integer.
Say you wanted to specify that one could supply _up to_ X number of items from Group A. Or supply at least 1 but no more than 3 from Group B.

Something like minCount, maxCount could support this.

**Comment by csuwildcat** [comment]
Can you give me a scenario where someone would be presented with an ask to submit between 2-5 things, and ever elect to submit more than 2?

**Comment by jenniferwiner** [comment]
How about employment? The ask would to present employment information: If the submitter has more than 1 job, they would submit more than one "thing"

Or a request for Race Information? (This may be a little too granular...) Usually when I see this on surveys/forms, you're requested to select at least one or more races.

**Comment by csuwildcat** [comment]
Those seem like valid cases - @wyc @brentzundel @glcohen what do you think?

**Comment by glcohen** [comment]
I agree they're valid cases. JSON Schema doesn't give us this flexibility, but I think it's worth adding min and maxCount selectors, which is more elegant than `AtLeastNOf` or UpToNOf`.

**Comment by csuwildcat** [comment]
@glcohen I think she's talking about the count stuff in the pick rule, which isn't based on JSON Schema, so we should be able to just add our own props to cover stuff like this, so long as we define them in normative text.

**Comment by wyc** [comment]
Thanks for the submission @jenniferwiner, and welcome!

Another use case: submit up to 20 bank statements in your name that sum to at least $100k.

I just wanted to note that this can also be implemented using pick-exactly functionality that exists today:
`pick 3-5` === `pick 3 | pick 4 | pick 5`

This means that if we make a change, then it is for convenience and shortening the length of PDs (`pick 1-10000` instead of `pick 1 | pick 2 | ...`). I'm very okay with this, just wanted to state the reasoning.

Finally, we need to decide if it's okay to overload these operators. Right now, if we implement a new rule like `pickRange`, it would apply to the input groups **and possibly also** to nested submission requirements. Does it make sense to pick 3-5 nested submission requirements to fulfill? Will qualifying logic meant against groups always apply to submission requirements and vice versa? If not, then we might:
(1) Make it harder for implementors who will need to double-implement each rule, once for input groups and once for nested submission requirements
(2) Stipulate that "this rule only applies to input groups" but cause worse usability when end users aren't sure which rules they can actually use for which type.

The other option is to not polymorphically overload the `for` property with `InputGroup | [SubmissionRequirement]`, and instead separate these into their own fields `for` and `nested`. At this point, would we use the same rule names in the `rule` property? Maybe there is a `nestedRule` instead. But of course all this adds complexity; I just wanted to air this issue in full.

**Comment by jenniferwiner** [comment]
Thanks for the welcome @wyc !! Ok so if I'm understanding, requesting 3 to 5 "things" currently could be accomplished by:
```
"submission_requirement": {
   ...
  "rule": "pick 1 | pick 2 | pick 3",
  "count": 1, // im assuming you'd leave count out in this case.
  "from": "B"
}
```

> Does it make sense to pick 3-5 nested submission requirements to fulfill? Will qualifying logic meant against groups always apply to submission requirements and vice versa?
This is a good point... Meaning how does the outer number of submission you supply interact with the inner number of submissions required/supplied? I could see the relationships getting complex here.

> The other option is to not polymorphically overload the `for` property with `InputGroup | [SubmissionRequirement]`,
Can you elaborate on the existing `for` property or what you mean by this?

**Comment by dtmcg** [comment]
@wyc An alternative to overloading operators is to apply rules which makes things explicit. We are dealing with categories which are the results of applying rules and the action we want to apply is over the union (or flattened) of these collections. 
R4<[VC]>(R3<[VC]>"A" ,  R1<[VC]>("B")): [VC]
...
  "rule": "pick",
  "floor": 2,
  "ceiling": 5,
  "from": [
	{
		"rule": "union",  "from": [{"rule": "all",  "from": "A"},
    							{"rule": "pick", "from": "B", "count": 2},]
	}    
  ]
...
or 
...
  "rule": "flatmap",
  "apply": 
  "from": [
	{
		"rule": "union",  "from": [{"rule": "all",  "from": "A"},
    								{"rule": "pick", "from": "B", "count": 2},]
	}    
  ]
...

**Comment by csuwildcat** [comment]
I am a fan of going with one of the following two paths that preserves the current simplicity of recursively applying the same logic that exists:

**1. Add more props to `pick`:**

```javascript
{
  "rule": "pick",
  "minimum": 2,
  "from": "B"
}

{
  "rule": "pick",
  "minimum": 2,
  "from": [
    { "rule": "all", "from": "A" },
    { "rule": "pick", "from": "B", "count": 1 },
    { "rule": "pick", "from": "C", "count": 1 },
  ]
}
```

**2. Add new rules to separate the different constructs:**

```javascript
{
  "rule": "minimum",
  "count": 2,
  "from": "B"
}

{
  "rule": "minimum",
  "count": 2,
  "from": [
    { "rule": "all", "from": "A" },
    { "rule": "pick", "from": "B", "count": 1 },
    { "rule": "pick", "from": "C", "count": 1 },
  ]
}
```

^^^ Both of these options preserve our current language while addressing the requirements.

**Comment by csuwildcat** [comment]
If we did the additional props route, we could just reuse the props defined in JSON Schema, and import those definitions, vs writing all of our own.

**Comment by glcohen** [comment]
+1 to adding new minimum and maximum props. And specify for use in top level only

**Comment by jenniferwiner** [comment]
minimum/maximum props w/ the `pick` rule would be my preference too. Is it intuitive that the "minimum" would be in reference to the count/items?

**Comment by csuwildcat** [comment]
To be specific, I propose we adopt the JSON Schema Number type keywords `minimum`, `exclusiveMinimum`, `maximum` and `exclusiveMaximum`, which enable common min/max needs, as well as range definition when used together, as seen here: https://json-schema.org/understanding-json-schema/reference/numeric.html#id7

**Comment by jenniferwiner** [comment]
I would lean towards using json schema array list (minItems, maxItems) rather than Number keywords since we're talking lists of things.

**Comment by csuwildcat** [comment]
@jenniferwiner given the selection is referential, it's not really important what the targets are, just that we satisfy the selection logic needs. There is a case to be made that if we are adopting a grammar, it is probably good to adopt the range grammar that allows for exclusive/inclusive min and max limits. Array keywords in JSON Schema don't provide for that option.

In terms of how count, minimum, maximum, etc. would 'go together' if they were all declared in one rule, we would just specify the spec language how keywords of greater specificity would override and how the fall through would work, and how logical evaluation would handle them (think something PEMDAS-esque). I'm just riffing, but you could write evaluation directives such as: "Evaluate exclusive min/max keywords first, then inclusive min/max, then count, if any fail, the rule declaration is not satisfied". Something like that would take care of any mixing of the 5 keywords.

**Comment by jenniferwiner** [comment]
@csuwildcat - Ah ok looking at the presentation submission target, i see what you're saying.... exclusive min/max could be useful for the requester. My only question though, since min/max/count keywords are always integers, the value would always be referring to the length of the list/number of items supplied, right?

Hierarchy of keyword makes a lot of sense -- thanks for clarifying.

**Comment by csuwildcat** [comment]
Upon reflection, I don't think there is a need for exclusive/inclusive distinction for range choice, at least for our use case. I have coded up the logic for the spec, assuming the addition of more simple `minimum` and `maximum` properties, which can be added to the `pick` rule and all intermixed via specificity ordering: https://codesandbox.io/s/gallant-bartik-cu8ns?file=/src/index.js. We can get all the flexibility desired across these requirements, along with unlimited nesting, in just a few lines of code, so I think this would be a good direction. This would mean we can keep just two rules and cover all our bases, without anything but some additional text to specify the min/max properties and the specificity order of property evaluation.

**Comment by jenniferwiner** [comment]
Would agree as well. The sandbox looks great - thanks for implementing. What are your contributing guidelines - let me know if i can help writing/wording at all.

**Comment by csuwildcat** [comment]
@jenniferwiner contribution will require being a signed Contributor to DIF in one of three ways:

1. If you are a lone person, not attached to some company with IP in the space, you would sign a Contributor agreement.
2. If you are a member of a company with work in the space, you should have them sign a DIF Associate Member agreement, which is now free for all companies under 1000 employees.
3. If you are a member of a company of > 1000 employees, you will need them to join as a paid DIF Associate member.

^ this will cover DIF and all the work against patent issues, and given you access to all the DIF calls, communication channels, etc. Other than that, you just need to gain general consensus support for your ideas/changes and have your PRs accepted by reviewers.

**Comment by glcohen** [comment]
@csuwildcat Jen is a part of our team at Workday

**Comment by jenniferwiner** [comment]
ah sorry should have pre-specified at I work with @glcohen. But thanks for the info and for taking up the issue!

**Comment by csuwildcat** [comment]
To record a decision, the proposal I will act on is as follows:

1. Make the top-level property `submission_requirements` and change the value to an array, to support more terse definition if you don't need nesting. 
2. Remove the polymorphism of the `from` field, and break it into `from_group` and `from_requirements`.
3. add the `minimum` and `maximum` properties to support all the different threshold and range variants desired.

Please +1 to signal that I should make these change, or -1 and comment with what about this proposal should be modified.

**Comment by wyc** [comment]
+1.

PS could also consider `from_nested`

**Comment by glcohen** [comment]
+1

nested is fine. I'm struggling with requirements, as the group is from requirements as well. maybe a simpler `from` and `from_nested`?

**Comment by csuwildcat** [comment]
Question: if we had just `from` and `from_nested`, would `from_nested` allow for group string refs? If not, we should probably be explicit.

**Comment by wyc** [comment]
I don't think `from_nested` should allow group string refs, and I don't follow your logic about being explicit. To me, the word "nested" generally implies self-similar structures, such as in the case of a nested for loop or nested code block.

**Comment by csuwildcat** [comment]
@wyc was just trying to make sure that we would not be allowing `from_nested` to have a mix of strings and objects.

**Comment by wyc** [comment]
Ah I see. Agreed. To be explicit: `from_nested` must have an array of Submission Requirement objects only. It cannot hold Strings directly. `from` needs a direct String, which represents an input group.

**Comment by glcohen** [comment]
would we be missing out of a possible combination if we specified `from_nested` could only have objects?

**Comment by wyc** [comment]
well--to be consistent, the top level `submission_requirements` should also only accept objects conforming to Submission Requirement as well, and not raw input group strings.

**Comment by csuwildcat** [comment]
Yes, the top-level would only contain objects, so I think it makes logical sense to do `from`/`from_nested`, and make `from_nested` strictly objects.

**Comment by glcohen** [comment]
+1 with `from`/`from_nested` with the restriction that nested can only contain objects

**Comment by csuwildcat** [comment]
Added in latest PR
