### ISSUE TITLE
support for did comm

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#58]
from #18 

> DIDComm is lower level than the problem domain of this spec. It allows transmission of arbitrary content, so it is capable of carrying the data formats described here, in the same way you could transmit the format over TCP.

> What's required in a DIDComm-based approach to communication is a higher-level protocol that explains the steps in the "dance" of proving something. This is the subject of Aries RFC 0037. That protocol, or future DIDComm based protocols like it, could be used to send a proof request (what is here called a "presentation definition") and receive a verifiable presentation (which could be wrapped in the presentation submission described here). The protocol is deliberately defined to be data format agnostic, so it is directly usable with this data format without modifying either doc.

> TODO: I recommend that you draw a distinction between the definition of a presentation (here called a "presentation definition", very appropriately) and the request for such a presentation. It seems quite likely to me that presentation definitions will be standardized and published. For example, there might be a standard presentation definition that captures the requirements of people applying for citizenship in a given country. Once defined, the actual interactions where proofs are demanded need not define them again; they might just refer to them. Thus, it is possible to REQUEST a presentation without DEFINING it, by simply refering to a previously published DEFINITION. This is why the Aries protocol describes the challenge for proof as a "request", not a "definition" -- a request could include an inlined definition, or simply refer to one that's external to the request.

as said by @OR13: 
> We need concrete examples of the JSON representation of the messages required to support this spec over didcomm

this is related to #52

**Comment by csuwildcat** [comment]
This appears to be a dupe: https://github.com/decentralized-identity/presentation-exchange/issues/52

I think that DID Comms support is inferred, given the PE data can exist within any type of other object being sent between participants. Can we converge these two Issues?

**Comment by brentzundel** [comment]
I'd like to keep this open at least until I've added an example of what using did comm to send a presentation request looks like.

**Comment by csuwildcat** [comment]
@TelegramSam @dhh1128 can you help us by providing a DIDComm message envelope we can use for showing DIDComm examples in the PE spec?

**Comment by swcurran** [comment]
I'll try to do that in a spec PR.  To summarize what it will be:

There is a "Present Proof" protocol (we should use v2.0 for this), and in it are messages - propose-presentation, request-presentation and presentation. In each message there is an attachment array that contains supported VC implementations (format/version).  The PE would be one such attachment for the request-presentation message (perhaps the only one over time), and the PS would be one such attachment for the "presentation" message.  Existing Aries AIP 1.0 agents have the current Indy presentation request and proof attachments. During a transition, both attachment types would be present in the request (from the verifier) and the holder would respond with one or the other.

**Comment by csuwildcat** [comment]
Propsal: @swcurran PR for specifying this

**Comment by csuwildcat** [comment]
@swcurran @TelegramSam can either of you supply Presentation Definition / Submission embed examples for DID Comms?

**Comment by swcurran** [comment]
I've not had time, but will try to get to it.  @llorllale had offered to do this as well, but as I type this, I'm not sure of his IPR status to do that.

**Comment by kdenhartog** [comment]
After PR #86 was merged I think this can be closed.
