### ISSUE TITLE
Use of "subject" as a role is misleading

### ISSUE THREAD

**Issue by pamelatech** [decentralized-identity/presentation-exchange#60]
The way that presentation exchange uses the term subject is misaligned with how both the verifiable credentials and the OpenID Connect world use the term. 

My suggestion would be to use relative roles for this case -- selecter and presenter.  This way, nobody gets confused about who is doing what, and we can layer presentation exchange as a flow overtop of any transport without collision of terms

**Comment by OR13** [comment]
strong +1.... we could probably safely find replace "Subject" with "Holder"... it is the "Holder" who makes presentations... and they might not the subject of the credentials.... Parents present credentials about children, pets, their car, etc...

**Comment by timcappalli** [comment]
+1 for holder

**Comment by swcurran** [comment]
+1 for Holder.  Or holder.  :-)

And a strong -1 for Subject.

**Comment by brentzundel** [comment]
fixed in PR #80, recommend closing
