### ISSUE TITLE
What are the requirements for the attribute selection language?

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/presentation-exchange#61]
We need a concrete set of requirements for the language a verifier will use to describe selection criteria in a presentation definition.

These requirements may include:
- the ability to use nested boolean expressions 
- selection of a number of items from a set.

are these required? what else is missing?

**Comment by csuwildcat** [comment]
I believe that is the scope of this, given we have abstracted actual input assessment from the selection path section (which is the right call, imo).

**Comment by csuwildcat** [comment]
Overarching Issue that Issue #56 falls under.

**Comment by csuwildcat** [comment]
Closed with recent spec decisions/updates
