### ISSUE TITLE
Example VCs of submissions doesnt make sense

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/presentation-exchange#68]
There is a bug in https://identity.foundation/presentation-exchange/#embed-targets there is two drivers license presentations in the submission. So the request does not matche the data itself.

There are multiple happnings of this, but this was one that was easy to see

**Comment by csuwildcat** [comment]
Proposal: clean up redundant example object

**Comment by csuwildcat** [comment]
Closed via merge of https://github.com/decentralized-identity/presentation-exchange/pull/83
