### ISSUE TITLE
Input Types: VC Type

### ISSUE THREAD

**Issue by dtmcg** [decentralized-identity/presentation-exchange#7]
For the VC type the following may be good to have. 

VC Input Request 
- Attribute specification 
- Optionality at the VC attribute level rather than the Input level to enable selective disclosure 
- It is an implicit requirement all the attributes returned for a given issue and schema must be fore, correlation of 

General Input Request
- Description (GDPR & UX Presentation)
- Reason (GDPR & Optional UX Presentation)
- Number of response elements e.g. 6 payslips for a bank loan. This is distinct from the existing pick selection. 

Note on typing of VCs in the Workday solution 
In the Workday Presentation requests, the credentials fields are typed by their Schemas, no further typing in the request is needed as he Verifier forms their query around their knowledge of the Schemas. 
Side note JSON Schema is used to specify the Credential field types. See: https://w3c-ccg.github.io/vc-json-schemas/

From : https://github.com/decentralized-identity/presentation-request/blob/master/proposals/presentation-message-format.md input_selection & input_descriptors
`{
"description": "6 Months of payslips",
"issuers": {
  "dids": [
    "did:work:EgLY8mysgbLmj542ygMKWo"
  ]
},
"max": 6,
"min": 6,
"reason": "Payslips are used to determine credit worthiness",
"schema": "did:work:KypRcDbLYAUwaA7nPuP3Tf;schema=1333;version=1.0",
"properties": [{
    "name": "currency",
    "required": true
  },
  {
    "name": "grossPay",
    "required": true
  },
  {
    "name": "payPeriodEnd",
    "required": true
  },
  {
    "name": "payPeriodStart",
    "required": true
  }
}`

**Comment by dtmcg** [comment]
Updated example selective disclosure with optional fields, cardinality of response, GDPR description and reason. 

`"input_descriptors": [
    {
      "type": "vc",
      "group": ["B"],
      "description": "Identification",
      "reason": "Regulatory requirements for identification",
      "schema": "https://eu.com/claims/IDCard",
      "constraints": {
        "issuers": ["did:foo:gov1", "did:bar:gov2"]
      }, 
      "max": 2,
      "min": 1,
      "credentialSubject" [{
            "name": "name",
            "required": false
          },
          {
            "name": "dob"
          },
          {
            "name": "picture",
            "required": true
          },
          {
            "name": "height",
            "required": false
          },
      ]    
    },
......
`

**Comment by David-Chadwick** [comment]
```
 {
               "name":"name",
               "required":false
            },
```
I see no reason to specify attributes that are not required. The only thing GDPR requires is minimum disclosure so simply specify the attributes that are required for the transaction to proceed

**Comment by OR13** [comment]
Any update on this? how do we move this issue forward?

**Comment by csuwildcat** [comment]
All inputs are assumed to be VCs now, so we should be able to close this as invalid now.

**Comment by csuwildcat** [comment]
Issue under old scheme, but changed to remove types.
