### ISSUE TITLE
The ability to explicitly state expectations around revocation

### ISSUE THREAD

**Issue by swcurran** [decentralized-identity/presentation-exchange#74]
We've been working with issuers and verifiers that may (or may not) be using revocation. I think there should be some ability for verifiers to express their expectations around revocation.  Defaults are relatively obvious ("credentials must not be revoked"), but there are some edge cases that we might want to enable.

* In some cases it is enough to prove possession of a credential, even if it has been revoked.
* The verifier should be able to say how fresh the revocation check must be. This is particularly interesting when using ZKPs that support revocation, where the prover does not share a unique ID for their credential, but rather proves that at a given point in time the credential was not revoked.
   * Since revocation registries may be updated at any time, it's a valid scenario that the proof could have been constructed before the most recent updates to the revocation registry.
   *  The holder should not be allowed to use that knowledge to prove non-revocation based on a revocation registry entry way back in the past.
       * Unless of course, this is an offline use case, or the prover is being asked to show their credential was not revoked way back in the past (say, during a court case -- "Doctor, was your credential valid at that time?").
* A single presentation generated by a holder may include claims (assertions) from credentials that support revocation and from those that don't.
   * This is more of an implementation issue, but the prover must be able to handle scenarios where revocation requirements are included in the Presentation Request whether or not the credentials they are holding can be revoked.

Similar edge case requirements occur around the expiration of a credential -- will the verifier accept an expired credential?

**Comment by glcohen** [comment]
This had been discussed a while back at a higher level. Expiration is already covered, since it's a [top-level property on VCs](https://w3c.github.io/vc-data-model/#expiration) you can request the expiration date from a given credential:

```
"constraints": {
          "fields": [
            {
              "path": ["$.expirationDate"],
              "purpose": "The credential must not be expired in the past week",
              "filter": {
                "type": "string",
                "format": "date-time",
                "minimum": "2020-01-01T19:23:24Z"
              }
            },...
```

Similar logic can be constructed if there is a well known revocation property. It looks like revocation can be implemented a few different ways (status list, non revocation proof, etc) which probably means a new `revocationStatus` field may need to be added to the spec here, covering all corner cases for different kinds of revocations.

I'd advocate for many of the specifics to not leak into this specification -- we can represent the general shape of a revocation across multiple revocation formats (general purpose revocation abstraction). We can then leave the 'how' for the revocation check to be left up to implementers.

**Comment by brentzundel** [comment]
Revocation status is also a [top level property on VCs](https://www.w3.org/TR/vc-data-model/#status)., so does that cover what is needed here?

**Comment by swcurran** [comment]
The challenge with revocation (and expiration) is that we will want the default to be "not revoked". If we handle it as @glcohen suggests above, the onus is on the verifier to always explicitly specify that they want "not expired" and "not revoked". What would be nice would be to make that implicit/default and make it explicit when you don't care about revocation / expiration.

**Comment by glcohen** [comment]
@swcurran your assessment is correct. the question is whether it is an implementation detail. baking in certain assumptions into the specification can lead us to a tricky place that makes the spec a bit harder to understand. leaving it as an explicit option leaves no room for confusion.

I do not imagine there will be _hundreds_ of implementations of this specification, but instead a few authoritative ones that can gain widespread adoption. Though empty now, I hope that we can fill [this repo](https://github.com/decentralized-identity/presentation-exchange-implementations) with implementations that abstract this kind of preference nicely.

**Comment by brentzundel** [comment]
Per the meeting on 9/3/2020: This issue brings up a gap in the existing specification language around revocation.
The verifier's default behavior is most likely going to be not accepting a revoked or expired credential.
@glcohen has accepted an action to make a proposal.

**Comment by glcohen** [comment]
Please review my changes. I need help with some examples outside VCs and cleaning up the language https://github.com/decentralized-identity/presentation-exchange/pull/104

**Comment by glcohen** [comment]
Moving this to `future` to track; there is an answer in for 0.1.0

**Comment by brentzundel** [comment]
based on conversation in meeting on 2022-03-24, we feel this has been addressed as well as it needs to be. Closing.
