### ISSUE TITLE
Contributor Guidelines document needed to issue call for broader community input

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/presentation-exchange#78]
At time of writing, DIDComm has this PDF linked from their homepage but not from the JS repo at dif:
https://drive.google.com/file/d/1gkzkEUw1oa8vECorlLBSRCp2vgT7aqmh/view
which links to this google doc that was never versioned/finalized:
https://docs.google.com/document/d/1TS4XXCtlNL9YwW-Op9alevOmhgY2RP6lFfQ3AtB6Sq8/edit#heading=h.sj76kg1msm6s

Happy to edit a version for this WG based on the DIDComm template that reflects conversations on today's call, which according to my call included the following specific imperatives:
1. 2 reviewers to close for all PRs, as soon as 2 business days later
2. Target state is next-call turnaround for any assigned issue, i.e., try to have a satisfactory PR 2 business days before next call if uncontroversial.

I will open a hackmd tonite to allow heavy editing and commenting until friday, then commit a "v0.1.0" to github some time after governance call for linking in the call for input next week?

**Comment by bumblefudge** [comment]
Additional points:
3.) reminder to use 80-char hardwraps in contributions, as we are in SPEC mode

**Comment by bumblefudge** [comment]
HackMD is here:
https://hackmd.io/vAW11ecIT2KO1R7EFkczWA

For people not familiar with HackMD, I cut and pasted the whole DIDComm input document in, and placed a "comment" in there so people using HackMD for the first time would have an example of a comment in there.

**Comment by wyc** [comment]
We will likely designate all sections as PROPOSED after adopting these guidelines, a signal that our very first cohesive iteration is out and ready for implementers to help refine.

**Comment by bumblefudge** [comment]
OK I think I got the most of it.  2 marginal comments pointing to parts that should be probably be addressed before bouncing at the world.  If anyone has strong opinions about, say, cutting entire sections, speak very very soon.

**Comment by wyc** [comment]
@bumblefudge are you able to make a PR for this later today? Happy to do so as well.

**Comment by bumblefudge** [comment]
I got some last-minute input that I just reflected in hackmd, if you could PR the current version that would be awesome. if not i will tomorrow.

**Comment by nembal** [comment]
I left a few comments in the doc. 
Most notably, I feel we should add a version control section.

**Comment by glcohen** [comment]
Resolved in #89
