### ISSUE TITLE
Suggestions -- add target data structure examples for Presentation Definition and pointers to details about the target data structures

### ISSUE THREAD

**Issue by swcurran** [decentralized-identity/presentation-exchange#87]
In adding the DIDComm Presentation Submission example, it wasn't clear to me why there was no comparable example for Presentation Definition.  Should there be?

Also, it seems to me that the target data structure examples are not very useful without a link to some context about the example data structure. I suggest adding a short section per target data structure to allow minimal narrative context and a link to additional detail to give a spec reader some context about the examples.

**Comment by csuwildcat** [comment]
Yes, there should be embed examples in the Definition section the same way there are in the Submission section - can you produce one for DIDComms for Definition as well?

**Comment by swcurran** [comment]
Yes - very similiar to the one below. If you could add a place to put in an example -- I'll put in the DIDComm example.

**Comment by brentzundel** [comment]
Addressed by PR #86
