### ISSUE TITLE
Terminology needs work.

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#90]
Based on the call today, I think it would be wise to create a terminology section, and note when we are using normative definitions from other specs, and when we are making up our own definitions... and not make up our own definitions that conflict....

I heard the word "Envelope" being used today... and I want to clarify the following.

An "Envelope" is some JSON you get.

The Envelope can be a VC Data Model VP (in LD or JWT form)
The Envelope can also be some JOSE based thing, like a DIDComm JWM, or an OIDC id_token.

We should be crystal clear that OIDC id_token's and DIDComm JWMs... ARE NOT W3C Verifiable Presentations...

its super confusing when we don't make this distinction, and we loose the ability to proxy requests over authenticated channels....

for example: Wallet -> VP -> CHAPI  (ENVELOPE)-> DIDComm  (ENVELOPE)-> OIDC (ENVELOPE)....

**Comment by csuwildcat** [comment]
How I see these terms is:

**Embed Targets**: the OIDC, DIDComm, CHAPI, etc. outer transport wrapper
**Inputs**: each atomic object/item you submit specific to an Input Descriptor, meaning: a JWT, a VC object, a VP object, a JWT of the VC/VP flavor, etc.

**Comment by glcohen** [comment]
Are embed targets always optional? Or do some inputs require (for best practices) an embed target?
I'm thinking that I _could_ just sent a VP, JWT, VC over HTTP without using an embed target.

**Comment by OR13** [comment]
`id_token`s would seem to require OIDC, but in reality, anyone can generate them, and its up to the verifier to decide if they will be accepted.

Similarly you can send a JWT / LDP ZKP over HTTP Signatures....

obviously if the verifier is running windows xp servers and only supports OIDC, you can't use DIDComm with them.

**Comment by glcohen** [comment]
I think that was one of the sources of confusion on yesterday's call. The language should be clear about how they can be optionally used together.

**Comment by OR13** [comment]
For example of terms used in respec: https://identity.foundation/.well-known/resources/did-configuration/#terminology

**Comment by csuwildcat** [comment]
> Are embed targets always optional? Or do some inputs require (for best practices) an embed target?
> I'm thinking that I _could_ just sent a VP, JWT, VC over HTTP without using an embed target.

Technically anything is an embed target, the simplest example being a plain JSON request body with a `presentation_submission` prop/object and a `credentials` prop/array with credentials inside. Random embed target? Presentation Exchange Badger don't care!

**Comment by brentzundel** [comment]
From the meeting 9/3/2020, we feel a terminology section is low effort and high value enough that it should be part of v0.1.0

**Comment by brentzundel** [comment]
@wyc will create a PR that introduces a terminology section with some initial values.

**Comment by brentzundel** [comment]
@glcohen and I agree that spending time on this issue during our call on 9/24/2020 would be valuable.

**Comment by wyc** [comment]
We did a terminology review here: https://hackmd.io/rTeaRlYLQlu753nuqAOQgw?both

The next steps are to organize this into logical groups and eliminate superfluous terminology across the spec.

**Comment by csuwildcat** [comment]
@wyc  any chance we could get an update on the status of this? This is the last major area of textual updates we wanted to get in for v1.0.

**Comment by wyc** [comment]
@csuwildcat I will spend time this weekend on it, including addressing concerns in #199. My apologies for all the delays.

**Comment by brentzundel** [comment]
I cleaned some of the terminology-related stuff in PR #192. We could probably close this when that merges.

**Comment by brentzundel** [comment]
#192 has been merged, closing
