### ISSUE TITLE
PE Spec defines a well known did configuration object schemas

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/presentation-exchange#94]
```
{
  "@context": "https://identity.foundation/.well-known/contexts/did-configuration-v0.0.jsonld",
  "linked_dids": [ VC_DATA_MODELs ],
  "supported_protocols": [ PROTOCOLs], // we are responsible for defining this data model.
  "credential_manifests": [ CREDENTIAL_MANIFESTS]
}
```

**Comment by OR13** [comment]
@csuwildcat to propose the data model for "supported_protocol" objects.

**Comment by OR13** [comment]
and "supported_formats" object...

**Comment by csuwildcat** [comment]
Update: supported formats is defined, and we should be able to reference it in DID Config now, if we want. Still need to talk with folks about the protocol stuff, as that may be better off located solely in DID Config

**Comment by csuwildcat** [comment]
Close as a possible deferral to DID Config
