### ISSUE TITLE
"Descriptor for ID Tokens" example in Section 5.2 is lacking context & definition

### ISSUE THREAD

**Issue by pamelatech** [decentralized-identity/presentation-exchange#96]
In section 5.2 (screenshot below) titled "input descriptors" there is an alternate "example" tab in the section that is poorly explained and whose context is not clear.  

Specific concerns include:
- the title of the example is "Descriptor for ID Tokens" but there is no object with the word descriptor in the example.  I assume that the parent object array was accidentally omitted 
- It isn't clear why there would be a mention of ID tokens in section 5 in the first place, as section 5 refers to the presentation request, and ID tokens generally are only used in presentation responses
- there are some plausible circumstances where an ID token might be part of an OpenID Connect authentication request, however if there is an expectation that a presentation definition should be embedded into that specific manifestation of an OpenID Connect request, it is not documented anywhere that I can find in the spec.

My recommendation would be to remove this example, and to add a section describing how a presentation definition might be embedded into an OpenID Connect request that is analogous to the "Embed Targets" part of section 6. 

![image](https://user-images.githubusercontent.com/2591320/91508368-37f3a000-e88c-11ea-9c84-cfb2e872ae9d.png)

**Comment by brentzundel** [comment]
from the meeting 9/3/2020: This may be better in an appendix.
this also brings up, "how does one include a presentation definition into an OIDC SIOP request?"
@pamelatech will propose some text for how MS is using them.
@wyc will raise a new issue to track the organization of the document part of the issue.

**Comment by brentzundel** [comment]
The concerns in this issue are being tracked in #100 and #101
