### ISSUE TITLE
Example of embedding Presentation Definition in a target data structure

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/presentation-exchange#97]
[Section 6.2](https://identity.foundation/presentation-exchange/#embed-targets) shows how to embed Presentation Submission within a target data structure (Verifiable Presentation, OIDC id token, etc.), however there is no equivalent for Presentation Definition in [Section 5](https://identity.foundation/presentation-exchange/#presentation-definition). It would be very helpful to have an example of embedding Presentation Definition in a target data structure too.

**Comment by brentzundel** [comment]
We have opened #100. Would that issue also address your concerns here? 
If so, should we close this issue?

**Comment by csuwildcat** [comment]
7 day close pending any new information.

**Comment by csuwildcat** [comment]
Going to close this out with collab at IIW: https://github.com/decentralized-identity/presentation-exchange/issues/100. Closing this Issue in favor of that other one.
