### ISSUE TITLE
new type of criterion in request for proof: which ledger backs the cred?

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/presentation-exchange#98]
This just surfaced as an idea at the Indy network-of-networks interopathon. Might a verifier want to be able to say, "Please prove this with a driver's license that is rooted on network X instead of network Y"?

@brentzundel

**Comment by glcohen** [comment]
Does the network matter as much as the issuer?
To fit this requirement we would need some canonical representation of networks, right? We have did method filtering for issuer paths that could be a substitute.

**Comment by dhh1128** [comment]
Yes, it's possible that did method filtering could be a substitute -- but in the case of Indy, we appear to be headed to having one DID method but many, many networks. You could even have one issuer operate on multiple networks.

It's possible that we just defer this. It's also possible that it isn't desirable, period. I just wanted to record the issue for discussion.

**Comment by glcohen** [comment]
How would networkness be enforced? Would the universal resolver specify the network of the DID?

**Comment by dhh1128** [comment]
>Would the universal resolver specify the network of the DID?

Maybe. That's a superb question for @peacekeeper ...

**Comment by brentzundel** [comment]
I think the mechanism we have for a verifier to specify approved issuers is sufficient to address this in v0.1.0, but we may want to revisit this question as the ecosystem matures.
