### ISSUE TITLE
Should Submission Requirements take precedence over Input Descriptors?

### ISSUE THREAD

**Issue by glcohen** [decentralized-identity/presentation-exchange#99]
Currently, Submission Requirements are optional. This means if a request has just Input Descriptors the expectation is that to *fulfill* the request, all Input Descriptors need to be satisfied.

However, if Submission Requirements are present, there is no requirement that they perfectly match to the Input Descriptors. The question is then, in the case of Submission Requirements and Input Descriptors, what is sufficient to satisfy the request?

I'd like to propose a change to specify that _if_ Submission Requirements are present, then satisfaction of those restraints are sufficient to fulfill the request; not both Submission Requirements AND Input Descriptors.

**Comment by csuwildcat** [comment]
@glcohen in my mind, it's definitely a case where both must be satisfied if present, because they're validating two separate things.

**Comment by glcohen** [comment]
I'm fine with that. The language definitely needs to be clearer:

1. Input Descriptors --> must satisfy all
2. Input Descriptors and Submission Requirements --> must satisfy both
3. No other valid combinations

**Comment by glcohen** [comment]
1. If no submission requirements, all input descriptors must be fulfilled
2. If submission requirements, all must be fulfilled. Input descriptors without a group tag must also be fulfilled

**Comment by glcohen** [comment]
Resolved with #102
